//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietSoft.CMMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietSoft.CMMS.Web.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu thành công..
        /// </summary>
        public static string APPLY_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("APPLY_REQUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt yêu cầu thành công..
        /// </summary>
        public static string APPROVAL_SUCCESS {
            get {
                return ResourceManager.GetString("APPROVAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        public static string CAPNHAT_THANHCONG {
            get {
                return ResourceManager.GetString("CAPNHAT_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        public static string CHANGE_PASS_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra..
        /// </summary>
        public static string COLOI_XAYRA {
            get {
                return ResourceManager.GetString("COLOI_XAYRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công..
        /// </summary>
        public static string DANGKY_THANHCONG {
            get {
                return ResourceManager.GetString("DANGKY_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống..
        /// </summary>
        public static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link đã hết hạn. Vui lòng gửi lại yêu cầu thay đổi mật khẩu và truy cập vào link mới..
        /// </summary>
        public static string LINK_FORGOT_PASS_EXPIRED {
            get {
                return ResourceManager.GetString("LINK_FORGOT_PASS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không đúng..
        /// </summary>
        public static string NHAPLAI_MK_KHONGDUNG {
            get {
                return ResourceManager.GetString("NHAPLAI_MK_KHONGDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này không có email. Vui lòng liên hệ quản trị viên để được trợ giúp..
        /// </summary>
        public static string SEND_MAIL_FAILED {
            get {
                return ResourceManager.GetString("SEND_MAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link tạo lại mật khẩu đã gửi đến {0}. Vui lòng kiểm tra mail của bạn..
        /// </summary>
        public static string SEND_MAIL_SUCCESS {
            get {
                return ResourceManager.GetString("SEND_MAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật yêu cầu thành công..
        /// </summary>
        public static string UPDATE_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_REQUEST_SUCCESS", resourceCulture);
            }
        }
    }
}
