//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietSoft.CMMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietSoft.CMMS.Web.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit request successfully..
        /// </summary>
        public static string APPLY_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("APPLY_REQUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse request successfully..
        /// </summary>
        public static string APPROVAL_SUCCESS {
            get {
                return ResourceManager.GetString("APPROVAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful..
        /// </summary>
        public static string CAPNHAT_THANHCONG {
            get {
                return ResourceManager.GetString("CAPNHAT_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successfully..
        /// </summary>
        public static string CHANGE_PASS_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move work through the master plan?.
        /// </summary>
        public static string CHUYEN_CONGVIEC_QUA_KEHOACH {
            get {
                return ResourceManager.GetString("CHUYEN_CONGVIEC_QUA_KEHOACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string COLOI_XAYRA {
            get {
                return ResourceManager.GetString("COLOI_XAYRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Success..
        /// </summary>
        public static string DANGKY_THANHCONG {
            get {
                return ResourceManager.GetString("DANGKY_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be left blank..
        /// </summary>
        public static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to lock this deposit slip?.
        /// </summary>
        public static string KHOA_PHIEU_NHAP {
            get {
                return ResourceManager.GetString("KHOA_PHIEU_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to lock this delivery note?.
        /// </summary>
        public static string KHOA_PHIEU_XUAT {
            get {
                return ResourceManager.GetString("KHOA_PHIEU_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has expired. Please resend the password change request and access the new link..
        /// </summary>
        public static string LINK_FORGOT_PASS_EXPIRED {
            get {
                return ResourceManager.GetString("LINK_FORGOT_PASS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spare parts for maintenance ticket.
        /// </summary>
        public static string MESS_CHUA_CO_PHU_TUNG {
            get {
                return ResourceManager.GetString("MESS_CHUA_CO_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value does not match!.
        /// </summary>
        public static string MESS_GIA_TRI_KHONG_HOP_LE {
            get {
                return ResourceManager.GetString("MESS_GIA_TRI_KHONG_HOP_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time has existed!.
        /// </summary>
        public static string MESS_KHOAN_TG_TON_TAI {
            get {
                return ResourceManager.GetString("MESS_KHOAN_TG_TON_TAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From day not greater to day!.
        /// </summary>
        public static string MESS_TN_KHONG_LON_HON_DN {
            get {
                return ResourceManager.GetString("MESS_TN_KHONG_LON_HON_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get older from now on.
        /// </summary>
        public static string MESS_TU_GIO_KHONG_LON_HON_DEN_GIO {
            get {
                return ResourceManager.GetString("MESS_TU_GIO_KHONG_LON_HON_DEN_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select data!.
        /// </summary>
        public static string MESS_VUI_LONG_CHON_DL {
            get {
                return ResourceManager.GetString("MESS_VUI_LONG_CHON_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect, please try again..
        /// </summary>
        public static string NHAPLAI_MK_KHONGDUNG {
            get {
                return ResourceManager.GetString("NHAPLAI_MK_KHONGDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has no email. Please contact your administrator for help..
        /// </summary>
        public static string SEND_MAIL_FAILED {
            get {
                return ResourceManager.GetString("SEND_MAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link sent to {0}. Please check your mail..
        /// </summary>
        public static string SEND_MAIL_SUCCESS {
            get {
                return ResourceManager.GetString("SEND_MAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update request successful..
        /// </summary>
        public static string UPDATE_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_REQUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to complete the maintenance ticket declaration?.
        /// </summary>
        public static string XACNHAN_HOANTHANH_PHIEUBAOTRI {
            get {
                return ResourceManager.GetString("XACNHAN_HOANTHANH_PHIEUBAOTRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this job?.
        /// </summary>
        public static string XOA_CONG_VIEC {
            get {
                return ResourceManager.GetString("XOA_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this voucher?.
        /// </summary>
        public static string XOA_NHAP_KHO {
            get {
                return ResourceManager.GetString("XOA_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this maintenance ticket?.
        /// </summary>
        public static string XOA_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("XOA_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this delivery note?.
        /// </summary>
        public static string XOA_PHIEU_XUAT {
            get {
                return ResourceManager.GetString("XOA_PHIEU_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the spare part for this stock receipt?.
        /// </summary>
        public static string XOA_PHU_TUNG_NHAP {
            get {
                return ResourceManager.GetString("XOA_PHU_TUNG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete spare parts for this delivery note?.
        /// </summary>
        public static string XOA_PHU_TUNG_XUAT {
            get {
                return ResourceManager.GetString("XOA_PHU_TUNG_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this request?.
        /// </summary>
        public static string XOA_YEU_CAU {
            get {
                return ResourceManager.GetString("XOA_YEU_CAU", resourceCulture);
            }
        }
    }
}
