//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietSoft.CMMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietSoft.CMMS.Web.Resources.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string BTN_BO_QUA {
            get {
                return ResourceManager.GetString("BTN_BO_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string BTN_DANGNHAP {
            get {
                return ResourceManager.GetString("BTN_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string BTN_DANGXUAT {
            get {
                return ResourceManager.GetString("BTN_DANGXUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string BTN_DOI_MK {
            get {
                return ResourceManager.GetString("BTN_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BTN_DONG {
            get {
                return ResourceManager.GetString("BTN_DONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse votes.
        /// </summary>
        public static string BTN_DUYET {
            get {
                return ResourceManager.GetString("BTN_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the WO.
        /// </summary>
        public static string BTN_HOAN_THANH_PBT {
            get {
                return ResourceManager.GetString("BTN_HOAN_THANH_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print QRCode.
        /// </summary>
        public static string BTN_IN_QR {
            get {
                return ResourceManager.GetString("BTN_IN_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string BTN_KHOA {
            get {
                return ResourceManager.GetString("BTN_KHOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not browse.
        /// </summary>
        public static string BTN_KHONG_DUYET {
            get {
                return ResourceManager.GetString("BTN_KHONG_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving on to the master plan.
        /// </summary>
        public static string BTN_LAP_KE_HOACH_TT {
            get {
                return ResourceManager.GetString("BTN_LAP_KE_HOACH_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a maintenance ticket.
        /// </summary>
        public static string BTN_LAP_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("BTN_LAP_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BTN_LUU {
            get {
                return ResourceManager.GetString("BTN_LUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save spare parts.
        /// </summary>
        public static string BTN_LUU_PHU_TUNG {
            get {
                return ResourceManager.GetString("BTN_LUU_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string BTN_QUEN_MK {
            get {
                return ResourceManager.GetString("BTN_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password.
        /// </summary>
        public static string BTN_TAOLAI_MK {
            get {
                return ResourceManager.GetString("BTN_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BTN_THEM {
            get {
                return ResourceManager.GetString("BTN_THEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string BTN_TRANG_CHU {
            get {
                return ResourceManager.GetString("BTN_TRANG_CHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Viewer.
        /// </summary>
        public static string BTN_XEM_TAI_LIEU {
            get {
                return ResourceManager.GetString("BTN_XEM_TAI_LIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BTN_XOA {
            get {
                return ResourceManager.GetString("BTN_XOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        public static string BTN_XOA_CONG_VIEC {
            get {
                return ResourceManager.GetString("BTN_XOA_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string LBL_AN_CHI_TIET {
            get {
                return ResourceManager.GetString("LBL_AN_CHI_TIET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string LBL_BAO_TRI {
            get {
                return ResourceManager.GetString("LBL_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string LBL_BO_PHAN_CHIEU_PHI {
            get {
                return ResourceManager.GetString("LBL_BO_PHAN_CHIEU_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string LBL_CA {
            get {
                return ResourceManager.GetString("LBL_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Method.
        /// </summary>
        public static string LBL_CACH_PHAN_BO {
            get {
                return ResourceManager.GetString("LBL_CACH_PHAN_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cost.
        /// </summary>
        public static string LBL_CHI_PHI_KHAC {
            get {
                return ResourceManager.GetString("LBL_CHI_PHI_KHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from WO.
        /// </summary>
        public static string LBL_CHON_TU_PBT {
            get {
                return ResourceManager.GetString("LBL_CHON_TU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved to.
        /// </summary>
        public static string LBL_CHUYEN_DEN {
            get {
                return ResourceManager.GetString("LBL_CHUYEN_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved from.
        /// </summary>
        public static string LBL_CHUYEN_DI {
            get {
                return ResourceManager.GetString("LBL_CHUYEN_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string LBL_CONG_VIEC {
            get {
                return ResourceManager.GetString("LBL_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR type.
        /// </summary>
        public static string LBL_DANG_NHAP {
            get {
                return ResourceManager.GetString("LBL_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI type.
        /// </summary>
        public static string LBL_DANG_XUAT {
            get {
                return ResourceManager.GetString("LBL_DANG_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till date.
        /// </summary>
        public static string LBL_DEN_NGAY_GIO {
            get {
                return ResourceManager.GetString("LBL_DEN_NGAY_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To time.
        /// </summary>
        public static string LBL_DENGIO {
            get {
                return ResourceManager.GetString("LBL_DENGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string LBL_DENNGAY {
            get {
                return ResourceManager.GetString("LBL_DENNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LBL_DIA_DIEM {
            get {
                return ResourceManager.GetString("LBL_DIA_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string LBL_DOI_MK {
            get {
                return ResourceManager.GetString("LBL_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string LBL_DON_GIA {
            get {
                return ResourceManager.GetString("LBL_DON_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        public static string LBL_DON_HANG {
            get {
                return ResourceManager.GetString("LBL_DON_HANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work unit.
        /// </summary>
        public static string LBL_DON_VI {
            get {
                return ResourceManager.GetString("LBL_DON_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string LBL_DUYET {
            get {
                return ResourceManager.GetString("LBL_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string LBL_GHI_CHU {
            get {
                return ResourceManager.GetString("LBL_GHI_CHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Work Time.
        /// </summary>
        public static string LBL_GHINHAN_THOIGIAN_LAMVIEC {
            get {
                return ResourceManager.GetString("LBL_GHINHAN_THOIGIAN_LAMVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string LBL_GIAM_SAT {
            get {
                return ResourceManager.GetString("LBL_GIAM_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Condition.
        /// </summary>
        public static string LBL_HIEN_TRANG_SD_MAY {
            get {
                return ResourceManager.GetString("LBL_HIEN_TRANG_SD_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LBL_HUY {
            get {
                return ResourceManager.GetString("LBL_HUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string LBL_KHO {
            get {
                return ResourceManager.GetString("LBL_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string LBL_KHONGCO_DULIEU {
            get {
                return ResourceManager.GetString("LBL_KHONGCO_DULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE HISTORY.
        /// </summary>
        public static string LBL_LICH_SU_BAO_TRI_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_LICH_SU_BAO_TRI_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance type.
        /// </summary>
        public static string LBL_LOAI_BT {
            get {
                return ResourceManager.GetString("LBL_LOAI_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Type.
        /// </summary>
        public static string LBL_LOAI_CP {
            get {
                return ResourceManager.GetString("LBL_LOAI_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Type.
        /// </summary>
        public static string LBL_LOAI_HC {
            get {
                return ResourceManager.GetString("LBL_LOAI_HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        public static string LBL_LOAI_MAY {
            get {
                return ResourceManager.GetString("LBL_LOAI_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        public static string LBL_LUU_DULIEU_DANGNHAP {
            get {
                return ResourceManager.GetString("LBL_LUU_DULIEU_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Code.
        /// </summary>
        public static string LBL_MA_BO_PHAN {
            get {
                return ResourceManager.GetString("LBL_MA_BO_PHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Part Code.
        /// </summary>
        public static string LBL_MA_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_MA_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Code.
        /// </summary>
        public static string LBL_MA_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_MA_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LBL_MATKHAU {
            get {
                return ResourceManager.GetString("LBL_MATKHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment to be handled.
        /// </summary>
        public static string LBL_MAY_CAN_XL {
            get {
                return ResourceManager.GetString("LBL_MAY_CAN_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown.
        /// </summary>
        public static string LBL_MAY_HONG {
            get {
                return ResourceManager.GetString("LBL_MAY_HONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status Description.
        /// </summary>
        public static string LBL_MO_TA_TINH_TRANG {
            get {
                return ResourceManager.GetString("LBL_MO_TA_TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI Code.
        /// </summary>
        public static string LBL_MS_PHIEU_NHAP {
            get {
                return ResourceManager.GetString("LBL_MS_PHIEU_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR Code.
        /// </summary>
        public static string LBL_MS_PHIEU_XUAT {
            get {
                return ResourceManager.GetString("LBL_MS_PHIEU_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Part Code.
        /// </summary>
        public static string LBL_MS_PT {
            get {
                return ResourceManager.GetString("LBL_MS_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LBL_NGAY {
            get {
                return ResourceManager.GetString("LBL_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        public static string LBL_NGAY_CHUNG_TU {
            get {
                return ResourceManager.GetString("LBL_NGAY_CHUNG_TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval date.
        /// </summary>
        public static string LBL_NGAY_DUYET {
            get {
                return ResourceManager.GetString("LBL_NGAY_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string LBL_NGAY_KT {
            get {
                return ResourceManager.GetString("LBL_NGAY_KT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        public static string LBL_NGAY_NHAP {
            get {
                return ResourceManager.GetString("LBL_NGAY_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive date.
        /// </summary>
        public static string LBL_NGAY_TIEP_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGAY_TIEP_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown Time.
        /// </summary>
        public static string LBL_NGAY_XAY_RA {
            get {
                return ResourceManager.GetString("LBL_NGAY_XAY_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string LBL_NGAY_XUAT {
            get {
                return ResourceManager.GetString("LBL_NGAY_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string LBL_NGAY_YC {
            get {
                return ResourceManager.GetString("LBL_NGAY_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string LBL_NGHIEM_THU {
            get {
                return ResourceManager.GetString("LBL_NGHIEM_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string LBL_NGUOI_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGUOI_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string LBL_NGUOI_NHAP {
            get {
                return ResourceManager.GetString("LBL_NGUOI_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        public static string LBL_NGUOI_THUC_HIEN {
            get {
                return ResourceManager.GetString("LBL_NGUOI_THUC_HIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string LBL_NGUOI_YEU_CAU {
            get {
                return ResourceManager.GetString("LBL_NGUOI_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string LBL_NGUYEN_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGUYEN_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LBL_NHAP_MK_MOI {
            get {
                return ResourceManager.GetString("LBL_NHAP_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received in Period.
        /// </summary>
        public static string LBL_NHAP_TRONG_KY {
            get {
                return ResourceManager.GetString("LBL_NHAP_TRONG_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinput New Password.
        /// </summary>
        public static string LBL_NHAPLAI_MK_MOI {
            get {
                return ResourceManager.GetString("LBL_NHAPLAI_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved to.
        /// </summary>
        public static string LBL_NOI_CHUYEN_DEN {
            get {
                return ResourceManager.GetString("LBL_NOI_CHUYEN_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved from.
        /// </summary>
        public static string LBL_NOI_CHUYEN_DI {
            get {
                return ResourceManager.GetString("LBL_NOI_CHUYEN_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Content.
        /// </summary>
        public static string LBL_NOI_DUNG_YC {
            get {
                return ResourceManager.GetString("LBL_NOI_DUNG_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage analysis by object.
        /// </summary>
        public static string LBL_PHAN_TICH_HU_HONG {
            get {
                return ResourceManager.GetString("LBL_PHAN_TICH_HU_HONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Analysis.
        /// </summary>
        public static string LBL_PHANTICH_HUHONG {
            get {
                return ResourceManager.GetString("LBL_PHANTICH_HUHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string LBL_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("LBL_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string LBL_PHONG_BAN {
            get {
                return ResourceManager.GetString("LBL_PHONG_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessary.
        /// </summary>
        public static string LBL_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string LBL_QUEN_MK {
            get {
                return ResourceManager.GetString("LBL_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Spare Part.
        /// </summary>
        public static string LBL_SCAN_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_SCAN_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Spare Part.
        /// </summary>
        public static string LBL_SCAN_VT_PT {
            get {
                return ResourceManager.GetString("LBL_SCAN_VT_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LBL_SEARCH {
            get {
                return ResourceManager.GetString("LBL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Qty.
        /// </summary>
        public static string LBL_SL_KHA_DUNG {
            get {
                return ResourceManager.GetString("LBL_SL_KHA_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Qty.
        /// </summary>
        public static string LBL_SL_THAY_THE {
            get {
                return ResourceManager.GetString("LBL_SL_THAY_THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Qty.
        /// </summary>
        public static string LBL_SL_TON_KHO {
            get {
                return ResourceManager.GetString("LBL_SL_TON_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty in WO.
        /// </summary>
        public static string LBL_SL_TREN_BT {
            get {
                return ResourceManager.GetString("LBL_SL_TREN_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Qty.
        /// </summary>
        public static string LBL_SO_CHUNG_TU {
            get {
                return ResourceManager.GetString("LBL_SO_CHUNG_TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string LBL_SO_LUONG {
            get {
                return ResourceManager.GetString("LBL_SO_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days.
        /// </summary>
        public static string LBL_SO_NGAY {
            get {
                return ResourceManager.GetString("LBL_SO_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LBL_SO_TIEN {
            get {
                return ResourceManager.GetString("LBL_SO_TIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LBL_TAOLAI_MK {
            get {
                return ResourceManager.GetString("LBL_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string LBL_TAT_CA {
            get {
                return ResourceManager.GetString("LBL_TAT_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string LBL_TEN_CV {
            get {
                return ResourceManager.GetString("LBL_TEN_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LBL_TEN_DANG_NHAP {
            get {
                return ResourceManager.GetString("LBL_TEN_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoM.
        /// </summary>
        public static string LBL_TEN_DVT {
            get {
                return ResourceManager.GetString("LBL_TEN_DVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Part Name.
        /// </summary>
        public static string LBL_TEN_PT {
            get {
                return ResourceManager.GetString("LBL_TEN_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maintennance Task.
        /// </summary>
        public static string LBL_THEM_CONGVIEC_BAOTRI {
            get {
                return ResourceManager.GetString("LBL_THEM_CONGVIEC_BAOTRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string LBL_THEM_HINH {
            get {
                return ResourceManager.GetString("LBL_THEM_HINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Spare Part.
        /// </summary>
        public static string LBL_THEM_PHUTUNG {
            get {
                return ResourceManager.GetString("LBL_THEM_PHUTUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string LBL_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine downtime.
        /// </summary>
        public static string LBL_THOI_GIAN_NGUNG_MAY {
            get {
                return ResourceManager.GetString("LBL_THOI_GIAN_NGUNG_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Parametter.
        /// </summary>
        public static string LBL_THONG_SO_DH {
            get {
                return ResourceManager.GetString("LBL_THONG_SO_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string LBL_THONG_TIN_NGUOI_DUNG {
            get {
                return ResourceManager.GetString("LBL_THONG_TIN_NGUOI_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string LBL_TIEN_TE {
            get {
                return ResourceManager.GetString("LBL_TIEN_TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string LBL_TINH_TRANG {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO Status.
        /// </summary>
        public static string LBL_TINH_TRANG_PBT {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Status.
        /// </summary>
        public static string LBL_TINH_TRANG_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string LBL_TO {
            get {
                return ResourceManager.GetString("LBL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock in Beginning.
        /// </summary>
        public static string LBL_TON_CUOI_KY {
            get {
                return ResourceManager.GetString("LBL_TON_CUOI_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock in End.
        /// </summary>
        public static string LBL_TON_DAU_KY {
            get {
                return ResourceManager.GetString("LBL_TON_DAU_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Part Replacement.
        /// </summary>
        public static string LBL_TT_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_TT_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status after Maintenance.
        /// </summary>
        public static string LBL_TT_SAU_BT {
            get {
                return ResourceManager.GetString("LBL_TT_SAU_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date and time.
        /// </summary>
        public static string LBL_TU_NGAY_GIO {
            get {
                return ResourceManager.GetString("LBL_TU_NGAY_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string LBL_TUNGAY {
            get {
                return ResourceManager.GetString("LBL_TUNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string LBL_UU_TIEN {
            get {
                return ResourceManager.GetString("LBL_UU_TIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %VAT.
        /// </summary>
        public static string LBL_VAT {
            get {
                return ResourceManager.GetString("LBL_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LBL_VI_TRI {
            get {
                return ResourceManager.GetString("LBL_VI_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Inventory.
        /// </summary>
        public static string LBL_XEM_TON_KHO {
            get {
                return ResourceManager.GetString("LBL_XEM_TON_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and enter downtime.
        /// </summary>
        public static string LBL_XEM_VA_NHAP_TGNM {
            get {
                return ResourceManager.GetString("LBL_XEM_VA_NHAP_TGNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued in Period.
        /// </summary>
        public static string LBL_XUAT_TRONG_KY {
            get {
                return ResourceManager.GetString("LBL_XUAT_TRONG_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string LBL_YEU_CAU {
            get {
                return ResourceManager.GetString("LBL_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Transaction Report.
        /// </summary>
        public static string MNU_BC_NHAP_XUAT_TON {
            get {
                return ResourceManager.GetString("MNU_BC_NHAP_XUAT_TON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MNU_DASHBOARD {
            get {
                return ResourceManager.GetString("MNU_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Movement.
        /// </summary>
        public static string MNU_DI_CHUYEN_TB {
            get {
                return ResourceManager.GetString("MNU_DI_CHUYEN_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Counting.
        /// </summary>
        public static string MNU_KIEM_KE {
            get {
                return ResourceManager.GetString("MNU_KIEM_KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance History.
        /// </summary>
        public static string MNU_LICH_SU_TB {
            get {
                return ResourceManager.GetString("MNU_LICH_SU_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Ecomaint.
        /// </summary>
        public static string MNU_MY_ECOMAINT {
            get {
                return ResourceManager.GetString("MNU_MY_ECOMAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO Acceptance.
        /// </summary>
        public static string MNU_NGHIEM_THU_PBT {
            get {
                return ResourceManager.GetString("MNU_NGHIEM_THU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receipt.
        /// </summary>
        public static string MNU_NHAP_KHO {
            get {
                return ResourceManager.GetString("MNU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintennance Request Follow up.
        /// </summary>
        public static string MNU_THEO_DOI_YC {
            get {
                return ResourceManager.GetString("MNU_THEO_DOI_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Issue.
        /// </summary>
        public static string MNU_XUAT_KHO {
            get {
                return ResourceManager.GetString("MNU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTORY TRANSACTION REPORT.
        /// </summary>
        public static string TITLE_BC_XUAT_NHAP_TON {
            get {
                return ResourceManager.GetString("TITLE_BC_XUAT_NHAP_TON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture.
        /// </summary>
        public static string TITLE_CHON_HINH_GIAM_SAT {
            get {
                return ResourceManager.GetString("TITLE_CHON_HINH_GIAM_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietSoft.
        /// </summary>
        public static string TITLE_CONGTY {
            get {
                return ResourceManager.GetString("TITLE_CONGTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string TITLE_DASH_BOARD {
            get {
                return ResourceManager.GetString("TITLE_DASH_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string TITLE_DOI_MK {
            get {
                return ResourceManager.GetString("TITLE_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF GOODS RECEIPTS.
        /// </summary>
        public static string TITLE_DS_PHIEU_NHAP_KHO {
            get {
                return ResourceManager.GetString("TITLE_DS_PHIEU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF GOODS ISSUE.
        /// </summary>
        public static string TITLE_DS_PHIEU_XUAT_KHO {
            get {
                return ResourceManager.GetString("TITLE_DS_PHIEU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse requests.
        /// </summary>
        public static string TITLE_DUYET_YC {
            get {
                return ResourceManager.GetString("TITLE_DUYET_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request not approved.
        /// </summary>
        public static string TITLE_KHONG_DUYET_YC {
            get {
                return ResourceManager.GetString("TITLE_KHONG_DUYET_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests are not accepted.
        /// </summary>
        public static string TITLE_KHONG_TIEP_NHAN_YC {
            get {
                return ResourceManager.GetString("TITLE_KHONG_TIEP_NHAN_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVICE INSPECTION.
        /// </summary>
        public static string TITLE_KIEM_KE_THIET_BI {
            get {
                return ResourceManager.GetString("TITLE_KIEM_KE_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENNANCE HISTORY.
        /// </summary>
        public static string TITLE_LICH_SU_YEU_CAU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_LICH_SU_YEU_CAU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ECOMAINT.
        /// </summary>
        public static string TITLE_MY_ECOMAIN {
            get {
                return ResourceManager.GetString("TITLE_MY_ECOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO ACCEPTANCE.
        /// </summary>
        public static string TITLE_NGHIEM_THU_PBT {
            get {
                return ResourceManager.GetString("TITLE_NGHIEM_THU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance of maintenance vouchers.
        /// </summary>
        public static string TITLE_NGHIEM_THU_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_NGHIEM_THU_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Landed Cost.
        /// </summary>
        public static string TITLE_NHAP_CHI_PHI {
            get {
                return ResourceManager.GetString("TITLE_NHAP_CHI_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Location.
        /// </summary>
        public static string TITLE_NHAP_VI_TRI_VTPT {
            get {
                return ResourceManager.GetString("TITLE_NHAP_VI_TRI_VTPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD ORDER.
        /// </summary>
        public static string TITLE_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOODS RECEIPT.
        /// </summary>
        public static string TITLE_PHIEU_NHAP_KHO {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOODS ISSUE.
        /// </summary>
        public static string TITLE_PHIEU_XUAT_KHO {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string TITLE_QUEN_MK {
            get {
                return ResourceManager.GetString("TITLE_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Passowrd.
        /// </summary>
        public static string TITLE_TAOLAI_MK {
            get {
                return ResourceManager.GetString("TITLE_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More implementers.
        /// </summary>
        public static string TITLE_THEN_NGUOI_THUC_HIEN {
            get {
                return ResourceManager.GetString("TITLE_THEN_NGUOI_THUC_HIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of maintenance ticket.
        /// </summary>
        public static string TITLE_THONG_TIN_PBT {
            get {
                return ResourceManager.GetString("TITLE_THONG_TIN_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE REQUEST.
        /// </summary>
        public static string TITLE_YEU_CAU_BT {
            get {
                return ResourceManager.GetString("TITLE_YEU_CAU_BT", resourceCulture);
            }
        }
    }
}
