//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietSoft.CMMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietSoft.CMMS.Web.Resources.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string BTN_CAPNHAT {
            get {
                return ResourceManager.GetString("BTN_CAPNHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        public static string BTN_DANGNHAP {
            get {
                return ResourceManager.GetString("BTN_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string BTN_DANGXUAT {
            get {
                return ResourceManager.GetString("BTN_DANGXUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string BTN_DOI_MK {
            get {
                return ResourceManager.GetString("BTN_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string BTN_DONG {
            get {
                return ResourceManager.GetString("BTN_DONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string BTN_DUYET {
            get {
                return ResourceManager.GetString("BTN_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        public static string BTN_GUIYEUCAU {
            get {
                return ResourceManager.GetString("BTN_GUIYEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string BTN_LUU {
            get {
                return ResourceManager.GetString("BTN_LUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        public static string BTN_QUEN_MK {
            get {
                return ResourceManager.GetString("BTN_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string BTN_TAOLAI_MK {
            get {
                return ResourceManager.GetString("BTN_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string BTN_TUCHOI {
            get {
                return ResourceManager.GetString("BTN_TUCHOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string BTN_XACNHAN {
            get {
                return ResourceManager.GetString("BTN_XACNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tháng.
        /// </summary>
        public static string DLL_CHONTHANG {
            get {
                return ResourceManager.GetString("DLL_CHONTHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string LABEL_BOPHAN {
            get {
                return ResourceManager.GetString("LABEL_BOPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string LABEL_CHUCVU {
            get {
                return ResourceManager.GetString("LABEL_CHUCVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu mật khẩu.
        /// </summary>
        public static string LABEL_LUU_DULIEU_DANGNHAP {
            get {
                return ResourceManager.GetString("LABEL_LUU_DULIEU_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số.
        /// </summary>
        public static string LABEL_MASO {
            get {
                return ResourceManager.GetString("LABEL_MASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào làm.
        /// </summary>
        public static string LABEL_NGAYVAOLAM {
            get {
                return ResourceManager.GetString("LABEL_NGAYVAOLAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string LABEL_TEN_NHANVIEN {
            get {
                return ResourceManager.GetString("LABEL_TEN_NHANVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ.
        /// </summary>
        public static string LABEL_TO {
            get {
                return ResourceManager.GetString("LABEL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ xí nghiệp.
        /// </summary>
        public static string LABEL_TOXINGHIEP {
            get {
                return ResourceManager.GetString("LABEL_TOXINGHIEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về.
        /// </summary>
        public static string LBL_TROVE {
            get {
                return ResourceManager.GetString("LBL_TROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỦY.
        /// </summary>
        public static string lLBL_HUY {
            get {
                return ResourceManager.GetString("lLBL_HUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG TY TNHH THÉP VINAONE.
        /// </summary>
        public static string TITLE_CONGTY {
            get {
                return ResourceManager.GetString("TITLE_CONGTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký nghỉ.
        /// </summary>
        public static string TITLE_DANGKY_NGHI {
            get {
                return ResourceManager.GetString("TITLE_DANGKY_NGHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string TITLE_DOI_MK {
            get {
                return ResourceManager.GetString("TITLE_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt nghỉ làm.
        /// </summary>
        public static string TITLE_DUYET_NGHI_LAM {
            get {
                return ResourceManager.GetString("TITLE_DUYET_NGHI_LAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ECOMAINT.
        /// </summary>
        public static string TITLE_MY_ECOMAIN {
            get {
                return ResourceManager.GetString("TITLE_MY_ECOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu lương tháng.
        /// </summary>
        public static string TITLE_PHIEULUONG_THANG {
            get {
                return ResourceManager.GetString("TITLE_PHIEULUONG_THANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string TITLE_QUEN_MK {
            get {
                return ResourceManager.GetString("TITLE_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string TITLE_TAOLAI_MK {
            get {
                return ResourceManager.GetString("TITLE_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        public static string TITLE_THONGTIN_NHANVIEN {
            get {
                return ResourceManager.GetString("TITLE_THONGTIN_NHANVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Lương sản phẩm.
        /// </summary>
        public static string TITLE_XEM_LUONG_SP {
            get {
                return ResourceManager.GetString("TITLE_XEM_LUONG_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem công.
        /// </summary>
        public static string TITLE_XEMCONG {
            get {
                return ResourceManager.GetString("TITLE_XEMCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHXH + BHYT + BHNT.
        /// </summary>
        public static string TXT_BHXH_BHYT_BHNT {
            get {
                return ResourceManager.GetString("TXT_BHXH_BHYT_BHNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để thay đổi mật khẩu ứng dụng, vui lòng truy cập.
        /// </summary>
        public static string TXT_CHANG_PASS_CONTENT {
            get {
                return ResourceManager.GetString("TXT_CHANG_PASS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết khoản nhận.
        /// </summary>
        public static string TXT_CHITIET_KHOANNHAN {
            get {
                return ResourceManager.GetString("TXT_CHITIET_KHOANNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết khoản trừ.
        /// </summary>
        public static string TXT_CHITIET_KHOANTRU {
            get {
                return ResourceManager.GetString("TXT_CHITIET_KHOANTRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian xin nghỉ bao gồm ngày cuối tuần, bạn có muốn tiếp tục?.
        /// </summary>
        public static string TXT_CONFIRM_WEEEKEND {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_WEEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công.
        /// </summary>
        public static string TXT_CONG {
            get {
                return ResourceManager.GetString("TXT_CONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nghỉ phép.
        /// </summary>
        public static string TXT_DA_NGHIPHEP {
            get {
                return ResourceManager.GetString("TXT_DA_NGHIPHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string TXT_DANGKY_THANHCONG {
            get {
                return ResourceManager.GetString("TXT_DANGKY_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến giờ.
        /// </summary>
        public static string TXT_DENGIO {
            get {
                return ResourceManager.GetString("TXT_DENGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string TXT_DENNGAY {
            get {
                return ResourceManager.GetString("TXT_DENNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string TXT_DIA_DIEM {
            get {
                return ResourceManager.GetString("TXT_DIA_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi muộn.
        /// </summary>
        public static string TXT_DIMUON {
            get {
                return ResourceManager.GetString("TXT_DIMUON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string TXT_DOI_MK {
            get {
                return ResourceManager.GetString("TXT_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng bảo hiểm.
        /// </summary>
        public static string TXT_DONG_BH {
            get {
                return ResourceManager.GetString("TXT_DONG_BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng quỹ công đoàn.
        /// </summary>
        public static string TXT_DONGQUY_CONGDOAN {
            get {
                return ResourceManager.GetString("TXT_DONGQUY_CONGDOAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string TXT_DUYET {
            get {
                return ResourceManager.GetString("TXT_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhận thời gian làm việc.
        /// </summary>
        public static string TXT_GHINHAN_THOIGIAN_LAMVIEC {
            get {
                return ResourceManager.GetString("TXT_GHINHAN_THOIGIAN_LAMVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giờ.
        /// </summary>
        public static string TXT_GIO {
            get {
                return ResourceManager.GetString("TXT_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giờ, 1 ngày.
        /// </summary>
        public static string TXT_GIO_NGAY {
            get {
                return ResourceManager.GetString("TXT_GIO_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ở đây.
        /// </summary>
        public static string TXT_HERE {
            get {
                return ResourceManager.GetString("TXT_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu..
        /// </summary>
        public static string TXT_KHONGCO_DULIEU {
            get {
                return ResourceManager.GetString("TXT_KHONGCO_DULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ BẢO TRÌ THIẾT BỊ.
        /// </summary>
        public static string TXT_LICH_SU_BAO_TRI_THIET_BI {
            get {
                return ResourceManager.GetString("TXT_LICH_SU_BAO_TRI_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ YÊU CẦU BẢO TRÌ.
        /// </summary>
        public static string TXT_LICH_SU_YEU_CAU_BAO_TRI {
            get {
                return ResourceManager.GetString("TXT_LICH_SU_YEU_CAU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương cơ bản.
        /// </summary>
        public static string TXT_LUONG_COBAN {
            get {
                return ResourceManager.GetString("TXT_LUONG_COBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương sản phẩm.
        /// </summary>
        public static string TXT_LUONG_SP {
            get {
                return ResourceManager.GetString("TXT_LUONG_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương sản phẩm mã hàng.
        /// </summary>
        public static string TXT_LUONG_SP_MAHANG {
            get {
                return ResourceManager.GetString("TXT_LUONG_SP_MAHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương tăng ca.
        /// </summary>
        public static string TXT_LUONG_TANGCA {
            get {
                return ResourceManager.GetString("TXT_LUONG_TANGCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận.
        /// </summary>
        public static string TXT_MA_BO_PHAN {
            get {
                return ResourceManager.GetString("TXT_MA_BO_PHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phụ tùng.
        /// </summary>
        public static string TXT_MA_PHU_TUNG {
            get {
                return ResourceManager.GetString("TXT_MA_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string TXT_MA_THIET_BI {
            get {
                return ResourceManager.GetString("TXT_MA_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        public static string TXT_MAHANG {
            get {
                return ResourceManager.GetString("TXT_MAHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số nhân viên.
        /// </summary>
        public static string TXT_MASO_NHANVIEN {
            get {
                return ResourceManager.GetString("TXT_MASO_NHANVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string TXT_MATKHAU {
            get {
                return ResourceManager.GetString("TXT_MATKHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày.
        /// </summary>
        public static string TXT_NGAY {
            get {
                return ResourceManager.GetString("TXT_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày công.
        /// </summary>
        public static string TXT_NGAYCONG {
            get {
                return ResourceManager.GetString("TXT_NGAYCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ theo giờ.
        /// </summary>
        public static string TXT_NGHI_THEOGIO {
            get {
                return ResourceManager.GetString("TXT_NGHI_THEOGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người yêu cầu.
        /// </summary>
        public static string TXT_NGUOI_YEU_CAU {
            get {
                return ResourceManager.GetString("TXT_NGUOI_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string TXT_NHAP_MK_MOI {
            get {
                return ResourceManager.GetString("TXT_NHAP_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string TXT_NHAPLAI_MK_MOI {
            get {
                return ResourceManager.GetString("TXT_NHAPLAI_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích hư hỏng.
        /// </summary>
        public static string TXT_PHANTICH_HUHONG {
            get {
                return ResourceManager.GetString("TXT_PHANTICH_HUHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chưa duyệt.
        /// </summary>
        public static string TXT_PHIEU_CHUADUYET {
            get {
                return ResourceManager.GetString("TXT_PHIEU_CHUADUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string TXT_QUEN_MK {
            get {
                return ResourceManager.GetString("TXT_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quỹ phép.
        /// </summary>
        public static string TXT_QUYPHEP {
            get {
                return ResourceManager.GetString("TXT_QUYPHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ra.
        /// </summary>
        public static string TXT_RA {
            get {
                return ResourceManager.GetString("TXT_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string TXT_SEARCH {
            get {
                return ResourceManager.GetString("TXT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số công TT.
        /// </summary>
        public static string TXT_SOCONG_TT {
            get {
                return ResourceManager.GetString("TXT_SOCONG_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ.
        /// </summary>
        public static string TXT_SOGIO {
            get {
                return ResourceManager.GetString("TXT_SOGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ / ngày.
        /// </summary>
        public static string TXT_SOGIO_NGAY {
            get {
                return ResourceManager.GetString("TXT_SOGIO_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ nghỉ hàng ngày.
        /// </summary>
        public static string TXT_SOGIO_NGHI_HANGNGAY {
            get {
                return ResourceManager.GetString("TXT_SOGIO_NGHI_HANGNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ tăng ca.
        /// </summary>
        public static string TXT_SOGIO_TANGCA {
            get {
                return ResourceManager.GetString("TXT_SOGIO_TANGCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần.
        /// </summary>
        public static string TXT_SOLAN {
            get {
                return ResourceManager.GetString("TXT_SOLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần đi muộn.
        /// </summary>
        public static string TXT_SOLAN_DIMUON {
            get {
                return ResourceManager.GetString("TXT_SOLAN_DIMUON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần về sớm.
        /// </summary>
        public static string TXT_SOLAN_VESOM {
            get {
                return ResourceManager.GetString("TXT_SOLAN_VESOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string TXT_SOLUONG {
            get {
                return ResourceManager.GetString("TXT_SOLUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày.
        /// </summary>
        public static string TXT_SONGAY {
            get {
                return ResourceManager.GetString("TXT_SONGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày vắng.
        /// </summary>
        public static string TXT_SONGAY_VANG {
            get {
                return ResourceManager.GetString("TXT_SONGAY_VANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phút.
        /// </summary>
        public static string TXT_SOPHUT {
            get {
                return ResourceManager.GetString("TXT_SOPHUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string TXT_TAB_CHITIET {
            get {
                return ResourceManager.GetString("TXT_TAB_CHITIET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        public static string TXT_TAB_TONGHOP {
            get {
                return ResourceManager.GetString("TXT_TAB_TONGHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng ca.
        /// </summary>
        public static string TXT_TANGCA {
            get {
                return ResourceManager.GetString("TXT_TANGCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string TXT_TAOLAI_MK {
            get {
                return ResourceManager.GetString("TXT_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công đoạn.
        /// </summary>
        public static string TXT_TEN_CONGDOAN {
            get {
                return ResourceManager.GetString("TXT_TEN_CONGDOAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string TXT_THANG {
            get {
                return ResourceManager.GetString("TXT_THANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string TXT_THANHTIEN {
            get {
                return ResourceManager.GetString("TXT_THANHTIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string TXT_THIET_BI {
            get {
                return ResourceManager.GetString("TXT_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng lương sản phẩm.
        /// </summary>
        public static string TXT_TONG_LUONG_SP {
            get {
                return ResourceManager.GetString("TXT_TONG_LUONG_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng phép.
        /// </summary>
        public static string TXT_TONG_PHEPNAM {
            get {
                return ResourceManager.GetString("TXT_TONG_PHEPNAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số giờ.
        /// </summary>
        public static string TXT_TONG_SOGIO {
            get {
                return ResourceManager.GetString("TXT_TONG_SOGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số ngày.
        /// </summary>
        public static string TXT_TONG_SONGAY {
            get {
                return ResourceManager.GetString("TXT_TONG_SONGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thành tiền.
        /// </summary>
        public static string TXT_TONG_THANHTIEN {
            get {
                return ResourceManager.GetString("TXT_TONG_THANHTIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng công.
        /// </summary>
        public static string TXT_TONGCONG {
            get {
                return ResourceManager.GetString("TXT_TONGCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thực nhận.
        /// </summary>
        public static string TXT_TONGCONG_THUCNHAN {
            get {
                return ResourceManager.GetString("TXT_TONGCONG_THUCNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng giờ làm.
        /// </summary>
        public static string TXT_TONGGIO_LAM {
            get {
                return ResourceManager.GetString("TXT_TONGGIO_LAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng giờ tăng ca.
        /// </summary>
        public static string TXT_TONGGIO_TANGCA {
            get {
                return ResourceManager.GetString("TXT_TONGGIO_TANGCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay thế phụ tùng.
        /// </summary>
        public static string TXT_TT_PHU_TUNG {
            get {
                return ResourceManager.GetString("TXT_TT_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string TXT_TUCHOI {
            get {
                return ResourceManager.GetString("TXT_TUCHOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ giờ.
        /// </summary>
        public static string TXT_TUGIO {
            get {
                return ResourceManager.GetString("TXT_TUGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string TXT_TUNGAY {
            get {
                return ResourceManager.GetString("TXT_TUNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào.
        /// </summary>
        public static string TXT_VAO {
            get {
                return ResourceManager.GetString("TXT_VAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về sớm.
        /// </summary>
        public static string TXT_VESOM {
            get {
                return ResourceManager.GetString("TXT_VESOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string TXT_XACNHAN {
            get {
                return ResourceManager.GetString("TXT_XACNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem lương sản phẩm.
        /// </summary>
        public static string TXT_XEM_LUONG_SP {
            get {
                return ResourceManager.GetString("TXT_XEM_LUONG_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem phiếu lương tháng.
        /// </summary>
        public static string TXT_XEM_PHIEULUONG_THANG {
            get {
                return ResourceManager.GetString("TXT_XEM_PHIEULUONG_THANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem công.
        /// </summary>
        public static string TXT_XEMCONG {
            get {
                return ResourceManager.GetString("TXT_XEMCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem lại.
        /// </summary>
        public static string TXT_XEMLAI {
            get {
                return ResourceManager.GetString("TXT_XEMLAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem phiếu cũ.
        /// </summary>
        public static string TXT_XEMPHIEUCU {
            get {
                return ResourceManager.GetString("TXT_XEMPHIEUCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ý kiến.
        /// </summary>
        public static string TXT_YKIEN {
            get {
                return ResourceManager.GetString("TXT_YKIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ý kiến cấp trên.
        /// </summary>
        public static string TXT_YKIEN_CAPTREN {
            get {
                return ResourceManager.GetString("TXT_YKIEN_CAPTREN", resourceCulture);
            }
        }
    }
}
