//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietSoft.CMMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietSoft.CMMS.Web.Resources.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        public static string BTN_BO_QUA {
            get {
                return ResourceManager.GetString("BTN_BO_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        public static string BTN_DANGNHAP {
            get {
                return ResourceManager.GetString("BTN_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string BTN_DANGXUAT {
            get {
                return ResourceManager.GetString("BTN_DANGXUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string BTN_DOI_MK {
            get {
                return ResourceManager.GetString("BTN_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string BTN_DONG {
            get {
                return ResourceManager.GetString("BTN_DONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt phiếu.
        /// </summary>
        public static string BTN_DUYET {
            get {
                return ResourceManager.GetString("BTN_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành phiếu.
        /// </summary>
        public static string BTN_HOAN_THANH_PBT {
            get {
                return ResourceManager.GetString("BTN_HOAN_THANH_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In QRCode.
        /// </summary>
        public static string BTN_IN_QR {
            get {
                return ResourceManager.GetString("BTN_IN_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa phiếu.
        /// </summary>
        public static string BTN_KHOA {
            get {
                return ResourceManager.GetString("BTN_KHOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không duyệt.
        /// </summary>
        public static string BTN_KHONG_DUYET {
            get {
                return ResourceManager.GetString("BTN_KHONG_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển qua kế hoạch tổng thể.
        /// </summary>
        public static string BTN_LAP_KE_HOACH_TT {
            get {
                return ResourceManager.GetString("BTN_LAP_KE_HOACH_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lập phiếu bảo trì.
        /// </summary>
        public static string BTN_LAP_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("BTN_LAP_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string BTN_LUU {
            get {
                return ResourceManager.GetString("BTN_LUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu phụ tùng.
        /// </summary>
        public static string BTN_LUU_PHU_TUNG {
            get {
                return ResourceManager.GetString("BTN_LUU_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        public static string BTN_QUEN_MK {
            get {
                return ResourceManager.GetString("BTN_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string BTN_TAOLAI_MK {
            get {
                return ResourceManager.GetString("BTN_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string BTN_THEM {
            get {
                return ResourceManager.GetString("BTN_THEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về trang chủ.
        /// </summary>
        public static string BTN_TRANG_CHU {
            get {
                return ResourceManager.GetString("BTN_TRANG_CHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tài liệu.
        /// </summary>
        public static string BTN_XEM_TAI_LIEU {
            get {
                return ResourceManager.GetString("BTN_XEM_TAI_LIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string BTN_XOA {
            get {
                return ResourceManager.GetString("BTN_XOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa công việc.
        /// </summary>
        public static string BTN_XOA_CONG_VIEC {
            get {
                return ResourceManager.GetString("BTN_XOA_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn chi tiết.
        /// </summary>
        public static string LBL_AN_CHI_TIET {
            get {
                return ResourceManager.GetString("LBL_AN_CHI_TIET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo trì.
        /// </summary>
        public static string LBL_BAO_TRI {
            get {
                return ResourceManager.GetString("LBL_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận CP.
        /// </summary>
        public static string LBL_BO_PHAN_CHIEU_PHI {
            get {
                return ResourceManager.GetString("LBL_BO_PHAN_CHIEU_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string LBL_CA {
            get {
                return ResourceManager.GetString("LBL_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cách phân bổ.
        /// </summary>
        public static string LBL_CACH_PHAN_BO {
            get {
                return ResourceManager.GetString("LBL_CACH_PHAN_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cách thực hiện.
        /// </summary>
        public static string LBL_CACH_THUC_HIEN {
            get {
                return ResourceManager.GetString("LBL_CACH_THUC_HIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí khác.
        /// </summary>
        public static string LBL_CHI_PHI_KHAC {
            get {
                return ResourceManager.GetString("LBL_CHI_PHI_KHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết công việc.
        /// </summary>
        public static string LBL_CHI_TIET_CV {
            get {
                return ResourceManager.GetString("LBL_CHI_TIET_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn công việc.
        /// </summary>
        public static string LBL_CHON_CONG_VIEC {
            get {
                return ResourceManager.GetString("LBL_CHON_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn từ phiếu bảo trì.
        /// </summary>
        public static string LBL_CHON_TU_PBT {
            get {
                return ResourceManager.GetString("LBL_CHON_TU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đến.
        /// </summary>
        public static string LBL_CHUYEN_DEN {
            get {
                return ResourceManager.GetString("LBL_CHUYEN_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đi.
        /// </summary>
        public static string LBL_CHUYEN_DI {
            get {
                return ResourceManager.GetString("LBL_CHUYEN_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc.
        /// </summary>
        public static string LBL_CONG_VIEC {
            get {
                return ResourceManager.GetString("LBL_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng nhập.
        /// </summary>
        public static string LBL_DANG_NHAP {
            get {
                return ResourceManager.GetString("LBL_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng xuất.
        /// </summary>
        public static string LBL_DANG_XUAT {
            get {
                return ResourceManager.GetString("LBL_DANG_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày giờ.
        /// </summary>
        public static string LBL_DEN_NGAY_GIO {
            get {
                return ResourceManager.GetString("LBL_DEN_NGAY_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến giờ.
        /// </summary>
        public static string LBL_DENGIO {
            get {
                return ResourceManager.GetString("LBL_DENGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string LBL_DENNGAY {
            get {
                return ResourceManager.GetString("LBL_DENNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string LBL_DIA_DIEM {
            get {
                return ResourceManager.GetString("LBL_DIA_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string LBL_DOI_MK {
            get {
                return ResourceManager.GetString("LBL_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string LBL_DON_GIA {
            get {
                return ResourceManager.GetString("LBL_DON_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string LBL_DON_HANG {
            get {
                return ResourceManager.GetString("LBL_DON_HANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string LBL_DON_VI {
            get {
                return ResourceManager.GetString("LBL_DON_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string LBL_DUYET {
            get {
                return ResourceManager.GetString("LBL_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string LBL_GHI_CHU {
            get {
                return ResourceManager.GetString("LBL_GHI_CHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhận thời gian làm việc.
        /// </summary>
        public static string LBL_GHINHAN_THOIGIAN_LAMVIEC {
            get {
                return ResourceManager.GetString("LBL_GHINHAN_THOIGIAN_LAMVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám sát.
        /// </summary>
        public static string LBL_GIAM_SAT {
            get {
                return ResourceManager.GetString("LBL_GIAM_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện Trạng Sử Dụng Máy.
        /// </summary>
        public static string LBL_HIEN_TRANG_SD_MAY {
            get {
                return ResourceManager.GetString("LBL_HIEN_TRANG_SD_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string LBL_HUY {
            get {
                return ResourceManager.GetString("LBL_HUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        public static string LBL_KHO {
            get {
                return ResourceManager.GetString("LBL_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu..
        /// </summary>
        public static string LBL_KHONGCO_DULIEU {
            get {
                return ResourceManager.GetString("LBL_KHONGCO_DULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ BẢO TRÌ THIẾT BỊ.
        /// </summary>
        public static string LBL_LICH_SU_BAO_TRI_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_LICH_SU_BAO_TRI_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại bảo trì.
        /// </summary>
        public static string LBL_LOAI_BT {
            get {
                return ResourceManager.GetString("LBL_LOAI_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chi phí.
        /// </summary>
        public static string LBL_LOAI_CP {
            get {
                return ResourceManager.GetString("LBL_LOAI_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại HC.
        /// </summary>
        public static string LBL_LOAI_HC {
            get {
                return ResourceManager.GetString("LBL_LOAI_HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị.
        /// </summary>
        public static string LBL_LOAI_MAY {
            get {
                return ResourceManager.GetString("LBL_LOAI_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu mật khẩu.
        /// </summary>
        public static string LBL_LUU_DULIEU_DANGNHAP {
            get {
                return ResourceManager.GetString("LBL_LUU_DULIEU_DANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận.
        /// </summary>
        public static string LBL_MA_BO_PHAN {
            get {
                return ResourceManager.GetString("LBL_MA_BO_PHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phụ tùng.
        /// </summary>
        public static string LBL_MA_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_MA_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string LBL_MA_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_MA_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string LBL_MATKHAU {
            get {
                return ResourceManager.GetString("LBL_MATKHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Những máy cần xử lý.
        /// </summary>
        public static string LBL_MAY_CAN_XL {
            get {
                return ResourceManager.GetString("LBL_MAY_CAN_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy hỏng.
        /// </summary>
        public static string LBL_MAY_HONG {
            get {
                return ResourceManager.GetString("LBL_MAY_HONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả tình trạng.
        /// </summary>
        public static string LBL_MO_TA_TINH_TRANG {
            get {
                return ResourceManager.GetString("LBL_MO_TA_TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS phiếu nhập.
        /// </summary>
        public static string LBL_MS_PHIEU_NHAP {
            get {
                return ResourceManager.GetString("LBL_MS_PHIEU_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS phiếu xuất.
        /// </summary>
        public static string LBL_MS_PHIEU_XUAT {
            get {
                return ResourceManager.GetString("LBL_MS_PHIEU_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã VTPT.
        /// </summary>
        public static string LBL_MS_PT {
            get {
                return ResourceManager.GetString("LBL_MS_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string LBL_NGAY {
            get {
                return ResourceManager.GetString("LBL_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string LBL_NGAY_CHUNG_TU {
            get {
                return ResourceManager.GetString("LBL_NGAY_CHUNG_TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày duyệt.
        /// </summary>
        public static string LBL_NGAY_DUYET {
            get {
                return ResourceManager.GetString("LBL_NGAY_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày KT.
        /// </summary>
        public static string LBL_NGAY_KT {
            get {
                return ResourceManager.GetString("LBL_NGAY_KT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập.
        /// </summary>
        public static string LBL_NGAY_NHAP {
            get {
                return ResourceManager.GetString("LBL_NGAY_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tiếp nhận.
        /// </summary>
        public static string LBL_NGAY_TIEP_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGAY_TIEP_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hỏng.
        /// </summary>
        public static string LBL_NGAY_XAY_RA {
            get {
                return ResourceManager.GetString("LBL_NGAY_XAY_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất.
        /// </summary>
        public static string LBL_NGAY_XUAT {
            get {
                return ResourceManager.GetString("LBL_NGAY_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày YC.
        /// </summary>
        public static string LBL_NGAY_YC {
            get {
                return ResourceManager.GetString("LBL_NGAY_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiệm thu.
        /// </summary>
        public static string LBL_NGHIEM_THU {
            get {
                return ResourceManager.GetString("LBL_NGHIEM_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người/Cty nhận.
        /// </summary>
        public static string LBL_NGUOI_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGUOI_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhập.
        /// </summary>
        public static string LBL_NGUOI_NHAP {
            get {
                return ResourceManager.GetString("LBL_NGUOI_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thực hiện.
        /// </summary>
        public static string LBL_NGUOI_THUC_HIEN {
            get {
                return ResourceManager.GetString("LBL_NGUOI_THUC_HIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người yêu cầu.
        /// </summary>
        public static string LBL_NGUOI_YEU_CAU {
            get {
                return ResourceManager.GetString("LBL_NGUOI_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên nhân.
        /// </summary>
        public static string LBL_NGUYEN_NHAN {
            get {
                return ResourceManager.GetString("LBL_NGUYEN_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string LBL_NHAP_MK_MOI {
            get {
                return ResourceManager.GetString("LBL_NHAP_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập trong kỳ.
        /// </summary>
        public static string LBL_NHAP_TRONG_KY {
            get {
                return ResourceManager.GetString("LBL_NHAP_TRONG_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string LBL_NHAPLAI_MK_MOI {
            get {
                return ResourceManager.GetString("LBL_NHAPLAI_MK_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi chuyển đến.
        /// </summary>
        public static string LBL_NOI_CHUYEN_DEN {
            get {
                return ResourceManager.GetString("LBL_NOI_CHUYEN_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi chuyển đi.
        /// </summary>
        public static string LBL_NOI_CHUYEN_DI {
            get {
                return ResourceManager.GetString("LBL_NOI_CHUYEN_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung yêu cầu.
        /// </summary>
        public static string LBL_NOI_DUNG_YC {
            get {
                return ResourceManager.GetString("LBL_NOI_DUNG_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích hư hỏng theo đối tượng.
        /// </summary>
        public static string LBL_PHAN_TICH_HU_HONG {
            get {
                return ResourceManager.GetString("LBL_PHAN_TICH_HU_HONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích hư hỏng &amp; TGNM.
        /// </summary>
        public static string LBL_PHANTICH_HUHONG {
            get {
                return ResourceManager.GetString("LBL_PHANTICH_HUHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu bảo trì.
        /// </summary>
        public static string LBL_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("LBL_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string LBL_PHONG_BAN {
            get {
                return ResourceManager.GetString("LBL_PHONG_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ tùng.
        /// </summary>
        public static string LBL_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string LBL_QUEN_MK {
            get {
                return ResourceManager.GetString("LBL_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan phụ tùng.
        /// </summary>
        public static string LBL_SCAN_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_SCAN_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan VTPT.
        /// </summary>
        public static string LBL_SCAN_VT_PT {
            get {
                return ResourceManager.GetString("LBL_SCAN_VT_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string LBL_SEARCH {
            get {
                return ResourceManager.GetString("LBL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL khả dụng.
        /// </summary>
        public static string LBL_SL_KHA_DUNG {
            get {
                return ResourceManager.GetString("LBL_SL_KHA_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng thay thế.
        /// </summary>
        public static string LBL_SL_THAY_THE {
            get {
                return ResourceManager.GetString("LBL_SL_THAY_THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL tồn kho.
        /// </summary>
        public static string LBL_SL_TON_KHO {
            get {
                return ResourceManager.GetString("LBL_SL_TON_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL trên PBT.
        /// </summary>
        public static string LBL_SL_TREN_BT {
            get {
                return ResourceManager.GetString("LBL_SL_TREN_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ.
        /// </summary>
        public static string LBL_SO_CHUNG_TU {
            get {
                return ResourceManager.GetString("LBL_SO_CHUNG_TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string LBL_SO_LUONG {
            get {
                return ResourceManager.GetString("LBL_SO_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày.
        /// </summary>
        public static string LBL_SO_NGAY {
            get {
                return ResourceManager.GetString("LBL_SO_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string LBL_SO_TIEN {
            get {
                return ResourceManager.GetString("LBL_SO_TIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string LBL_TAOLAI_MK {
            get {
                return ResourceManager.GetString("LBL_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string LBL_TAT_CA {
            get {
                return ResourceManager.GetString("LBL_TAT_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công việc.
        /// </summary>
        public static string LBL_TEN_CV {
            get {
                return ResourceManager.GetString("LBL_TEN_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string LBL_TEN_DANG_NHAP {
            get {
                return ResourceManager.GetString("LBL_TEN_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string LBL_TEN_DVT {
            get {
                return ResourceManager.GetString("LBL_TEN_DVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên VTPT.
        /// </summary>
        public static string LBL_TEN_PT {
            get {
                return ResourceManager.GetString("LBL_TEN_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm công việc.
        /// </summary>
        public static string LBL_THEM_CONG_VIEC {
            get {
                return ResourceManager.GetString("LBL_THEM_CONG_VIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm công việc bảo trì.
        /// </summary>
        public static string LBL_THEM_CONGVIEC_BAOTRI {
            get {
                return ResourceManager.GetString("LBL_THEM_CONGVIEC_BAOTRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hình.
        /// </summary>
        public static string LBL_THEM_HINH {
            get {
                return ResourceManager.GetString("LBL_THEM_HINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vật tư phụ tùng  .
        /// </summary>
        public static string LBL_THEM_PHUTUNG {
            get {
                return ResourceManager.GetString("LBL_THEM_PHUTUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string LBL_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chuẩn(phút).
        /// </summary>
        public static string LBL_THOI_GIAN_CHUAN {
            get {
                return ResourceManager.GetString("LBL_THOI_GIAN_CHUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian ngừng máy.
        /// </summary>
        public static string LBL_THOI_GIAN_NGUNG_MAY {
            get {
                return ResourceManager.GetString("LBL_THOI_GIAN_NGUNG_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Những thông số đến hạn.
        /// </summary>
        public static string LBL_THONG_SO_DH {
            get {
                return ResourceManager.GetString("LBL_THONG_SO_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Người Dùng.
        /// </summary>
        public static string LBL_THONG_TIN_NGUOI_DUNG {
            get {
                return ResourceManager.GetString("LBL_THONG_TIN_NGUOI_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền tệ.
        /// </summary>
        public static string LBL_TIEN_TE {
            get {
                return ResourceManager.GetString("LBL_TIEN_TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn kiểm tra.
        /// </summary>
        public static string LBL_TIEU_CHUAN_KTRA {
            get {
                return ResourceManager.GetString("LBL_TIEU_CHUAN_KTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string LBL_TINH_TRANG {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trạng Phiếu Bảo Trì.
        /// </summary>
        public static string LBL_TINH_TRANG_PBT {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trang Thiết Bị.
        /// </summary>
        public static string LBL_TINH_TRANG_THIET_BI {
            get {
                return ResourceManager.GetString("LBL_TINH_TRANG_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ.
        /// </summary>
        public static string LBL_TO {
            get {
                return ResourceManager.GetString("LBL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn cuối kỳ.
        /// </summary>
        public static string LBL_TON_CUOI_KY {
            get {
                return ResourceManager.GetString("LBL_TON_CUOI_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn đầu kỳ.
        /// </summary>
        public static string LBL_TON_DAU_KY {
            get {
                return ResourceManager.GetString("LBL_TON_DAU_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay thế phụ tùng.
        /// </summary>
        public static string LBL_TT_PHU_TUNG {
            get {
                return ResourceManager.GetString("LBL_TT_PHU_TUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng sau bảo trì.
        /// </summary>
        public static string LBL_TT_SAU_BT {
            get {
                return ResourceManager.GetString("LBL_TT_SAU_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày giờ.
        /// </summary>
        public static string LBL_TU_NGAY_GIO {
            get {
                return ResourceManager.GetString("LBL_TU_NGAY_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string LBL_TUNGAY {
            get {
                return ResourceManager.GetString("LBL_TUNGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức độ khẩn cấp.
        /// </summary>
        public static string LBL_UU_TIEN {
            get {
                return ResourceManager.GetString("LBL_UU_TIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Vat.
        /// </summary>
        public static string LBL_VAT {
            get {
                return ResourceManager.GetString("LBL_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string LBL_VI_TRI {
            get {
                return ResourceManager.GetString("LBL_VI_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tồn kho.
        /// </summary>
        public static string LBL_XEM_TON_KHO {
            get {
                return ResourceManager.GetString("LBL_XEM_TON_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem và nhập thời gian ngừng máy.
        /// </summary>
        public static string LBL_XEM_VA_NHAP_TGNM {
            get {
                return ResourceManager.GetString("LBL_XEM_VA_NHAP_TGNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất trong kỳ.
        /// </summary>
        public static string LBL_XUAT_TRONG_KY {
            get {
                return ResourceManager.GetString("LBL_XUAT_TRONG_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu.
        /// </summary>
        public static string LBL_YEU_CAU {
            get {
                return ResourceManager.GetString("LBL_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu dụng cụ.
        /// </summary>
        public static string LBL_YEU_CAU_DC {
            get {
                return ResourceManager.GetString("LBL_YEU_CAU_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhân sự.
        /// </summary>
        public static string LBL_YEU_CAU_NS {
            get {
                return ResourceManager.GetString("LBL_YEU_CAU_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo xuất nhập tồn.
        /// </summary>
        public static string MNU_BC_NHAP_XUAT_TON {
            get {
                return ResourceManager.GetString("MNU_BC_NHAP_XUAT_TON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MNU_DASHBOARD {
            get {
                return ResourceManager.GetString("MNU_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển thiết bị.
        /// </summary>
        public static string MNU_DI_CHUYEN_TB {
            get {
                return ResourceManager.GetString("MNU_DI_CHUYEN_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê thiết bị.
        /// </summary>
        public static string MNU_KIEM_KE {
            get {
                return ResourceManager.GetString("MNU_KIEM_KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử bảo trì thiết bị.
        /// </summary>
        public static string MNU_LICH_SU_TB {
            get {
                return ResourceManager.GetString("MNU_LICH_SU_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Ecomaint.
        /// </summary>
        public static string MNU_MY_ECOMAINT {
            get {
                return ResourceManager.GetString("MNU_MY_ECOMAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiệm thu phiếu bảo trì.
        /// </summary>
        public static string MNU_NGHIEM_THU_PBT {
            get {
                return ResourceManager.GetString("MNU_NGHIEM_THU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        public static string MNU_NHAP_KHO {
            get {
                return ResourceManager.GetString("MNU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi yêu cầu bảo trì.
        /// </summary>
        public static string MNU_THEO_DOI_YC {
            get {
                return ResourceManager.GetString("MNU_THEO_DOI_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        public static string MNU_XUAT_KHO {
            get {
                return ResourceManager.GetString("MNU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CÁO XUẤT NHẬP TỒN.
        /// </summary>
        public static string TITLE_BC_XUAT_NHAP_TON {
            get {
                return ResourceManager.GetString("TITLE_BC_XUAT_NHAP_TON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình cho giám sát.
        /// </summary>
        public static string TITLE_CHON_HINH_GIAM_SAT {
            get {
                return ResourceManager.GetString("TITLE_CHON_HINH_GIAM_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietSoft.
        /// </summary>
        public static string TITLE_CONGTY {
            get {
                return ResourceManager.GetString("TITLE_CONGTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string TITLE_DASH_BOARD {
            get {
                return ResourceManager.GetString("TITLE_DASH_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string TITLE_DOI_MK {
            get {
                return ResourceManager.GetString("TITLE_DOI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH PHIẾU NHẬP KHO.
        /// </summary>
        public static string TITLE_DS_PHIEU_NHAP_KHO {
            get {
                return ResourceManager.GetString("TITLE_DS_PHIEU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH PHIẾU XUẤT KHO.
        /// </summary>
        public static string TITLE_DS_PHIEU_XUAT_KHO {
            get {
                return ResourceManager.GetString("TITLE_DS_PHIEU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt yêu cầu.
        /// </summary>
        public static string TITLE_DUYET_YC {
            get {
                return ResourceManager.GetString("TITLE_DUYET_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không duyệt yêu cầu.
        /// </summary>
        public static string TITLE_KHONG_DUYET_YC {
            get {
                return ResourceManager.GetString("TITLE_KHONG_DUYET_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tiếp nhận yêu cầu.
        /// </summary>
        public static string TITLE_KHONG_TIEP_NHAN_YC {
            get {
                return ResourceManager.GetString("TITLE_KHONG_TIEP_NHAN_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIỂM KÊ THIẾT BỊ.
        /// </summary>
        public static string TITLE_KIEM_KE_THIET_BI {
            get {
                return ResourceManager.GetString("TITLE_KIEM_KE_THIET_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ YÊU CẦU BẢO TRÌ.
        /// </summary>
        public static string TITLE_LICH_SU_YEU_CAU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_LICH_SU_YEU_CAU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ECOMAINT.
        /// </summary>
        public static string TITLE_MY_ECOMAIN {
            get {
                return ResourceManager.GetString("TITLE_MY_ECOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGHIỆM THU PHIẾU BẢO TRÌ.
        /// </summary>
        public static string TITLE_NGHIEM_THU_PBT {
            get {
                return ResourceManager.GetString("TITLE_NGHIEM_THU_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiệm thu phiếu bảo trì.
        /// </summary>
        public static string TITLE_NGHIEM_THU_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_NGHIEM_THU_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập chi phí mua hàng.
        /// </summary>
        public static string TITLE_NHAP_CHI_PHI {
            get {
                return ResourceManager.GetString("TITLE_NHAP_CHI_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập vị trí VTPT.
        /// </summary>
        public static string TITLE_NHAP_VI_TRI_VTPT {
            get {
                return ResourceManager.GetString("TITLE_NHAP_VI_TRI_VTPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU BẢO TRÌ.
        /// </summary>
        public static string TITLE_PHIEU_BAO_TRI {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_BAO_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU NHẬP KHO.
        /// </summary>
        public static string TITLE_PHIEU_NHAP_KHO {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU XUẤT KHO.
        /// </summary>
        public static string TITLE_PHIEU_XUAT_KHO {
            get {
                return ResourceManager.GetString("TITLE_PHIEU_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string TITLE_QUEN_MK {
            get {
                return ResourceManager.GetString("TITLE_QUEN_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string TITLE_TAOLAI_MK {
            get {
                return ResourceManager.GetString("TITLE_TAOLAI_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm công việc cấu trúc.
        /// </summary>
        public static string TITLE_THEM_CONG_VIEC_CAU_TRUC {
            get {
                return ResourceManager.GetString("TITLE_THEM_CONG_VIEC_CAU_TRUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm người thực hiện.
        /// </summary>
        public static string TITLE_THEN_NGUOI_THUC_HIEN {
            get {
                return ResourceManager.GetString("TITLE_THEN_NGUOI_THUC_HIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin phiếu bảo trì.
        /// </summary>
        public static string TITLE_THONG_TIN_PBT {
            get {
                return ResourceManager.GetString("TITLE_THONG_TIN_PBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÊU CẦU BẢO TRÌ.
        /// </summary>
        public static string TITLE_YEU_CAU_BT {
            get {
                return ResourceManager.GetString("TITLE_YEU_CAU_BT", resourceCulture);
            }
        }
    }
}
