--WO-201401000001
--WR-201406000006
CREATE FUNCTION [dbo].[AUTO_CREATE_SO_PHIEU_BT] (
	@DATE DATETIME )
	RETURNS NVARCHAR(15)
AS 
BEGIN
DECLARE @STTMAX INT 
SELECT 
@STTMAX = MAX(CONVERT(INT,RIGHT (MS_PHIEU_BAO_TRI,6)))  
FROM dbo.PHIEU_BAO_TRI
WHERE  LEFT(MS_PHIEU_BAO_TRI,2) = 'WO' AND SUBSTRING(MS_PHIEU_BAO_TRI,4,6) = CONVERT(NVARCHAR(6) , @DATE , 112)

DECLARE @STT_NEXT NVARCHAR(10)
SET @STT_NEXT =  '000000' + CONVERT(NVARCHAR(6),ISNULL(@STTMAX,0) +1)

--SELECT @STT_NEXT 

DECLARE @ID NVARCHAR(15)
SET @ID = 'WO-' +  CONVERT(NVARCHAR(6) , @DATE , 112) +  RIGHT (@STT_NEXT,6)
RETURN @ID
END
GO

