
CREATE FUNCTION [dbo].[AUTO_CREATE_SO_PHIEU_YC] (
	@DATE DATETIME )
	RETURNS NVARCHAR(15)
AS 
BEGIN
DECLARE @STTMAX INT 
SELECT 
@STTMAX = MAX(CONVERT(INT,RIGHT (SO_YEU_CAU,6)))  
FROM dbo.YEU_CAU_NSD
WHERE  LEFT(SO_YEU_CAU,2) = 'WR' AND SUBSTRING(SO_YEU_CAU,4,6) = CONVERT(NVARCHAR(6) , @DATE , 112)

DECLARE @STT_NEXT NVARCHAR(10)
SET @STT_NEXT =  '000000' + CONVERT(NVARCHAR(6),ISNULL(@STTMAX,0) +1)

--SELECT @STT_NEXT 

DECLARE @ID NVARCHAR(15)
SET @ID = 'WR-' +  CONVERT(NVARCHAR(6) , @DATE , 112) +  RIGHT (@STT_NEXT,6)
RETURN @ID
END
GO

