ALTER PROCEDURE [dbo].[CheckPHIEU_BAO_TRI]
@MS_PHIEU_BAO_TRI NVARCHAR(20)
 AS
DECLARE @TMP NVARCHAR(20)
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM EOR_CONG_VIEC WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_CONG_VIEC WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_CHI_PHI WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_CONG_VIEC WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_DI_CHUYEN_BP WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_CV_PHU_TRO WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_HINH WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PHIEU_BAO_TRI  FROM PHIEU_BAO_TRI_SERVICE WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PHIEU_BAO_TRI FROM EOR_CONG_VIEC_PHU_TRO WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PHIEU_BAO_TRI FROM MAY_PHAN_BO_ATT WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PHIEU_BAO_TRI FROM IC_DON_HANG_XUAT WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PBT FROM dbo.THOI_GIAN_DUNG_MAY WHERE MS_PBT=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CLASS WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP= MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_TINH_TRANG WHERE MS_PHIEU_BAO_TRI=@MS_PHIEU_BAO_TRI
SELECT @TMP=MS_PBT FROM GIAM_SAT_TINH_TRANG_TS WHERE  MS_PBT =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PBT FROM GIAM_SAT_TINH_TRANG_TS_DT WHERE  MS_PBT =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM IC_DON_HANG_XUAT WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM IC_DON_HANG_XUAT_X WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM KE_HOACH_TONG_CONG_VIEC WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CHI_PHI WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CLASS WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_KE_HOACH WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_CHI_TIET WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_NHAN_SU_PHU_TRO WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CONG_VIEC_PHU_TUNG_CHI_TIET_KHO WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CV_KH_PHU_TRO WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CV_PHU_TRO WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_CV_PHU_TRO_NHAN_SU WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PBT FROM PHIEU_BAO_TRI_DANH_GIA_SERVICE WHERE  MS_PBT =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_DI_CHUYEN_BP WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_GIAM_SAT_NGHIEM_THU WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_HINH WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_PHAN_HOI_THONG_TIN WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_SERVICE WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_TINH_TRANG WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM TB_PHU_TUNG_BAO_TRI WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PHIEU_BAO_TRI FROM TB_VAT_TU_BAO_TRI WHERE  MS_PHIEU_BAO_TRI =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PBT FROM THOI_GIAN_CHAY_MAY WHERE  MS_PBT =  @MS_PHIEU_BAO_TRI 
SELECT @TMP=MS_PBT FROM YEU_CAU_NSD_CHI_TIET WHERE  MS_PBT =  @MS_PHIEU_BAO_TRI 
SELECT @TMP AS MS_PHIEU_BAO_TRI
GO
ALTER PROC [dbo].[S_PHIEU_BAO_TRI_NEW]
	@USERNAME NVARCHAR(50) = 'admin',
	@TUNGAY NVARCHAR(10) = '07/01/2019',
	@DENNGAY NVARCHAR(10) = '07/30/2019',
	@NGHIEMTHU INT = 2,
	@LOAY_MAY NVARCHAR(200) = '-1',
    @NHOM_MAY NVARCHAR(100) = '-1',
	@MS_MAY NVARCHAR(100) = '-1',
	@MS_NHA_XUONG NVARCHAR(50) = '-1',
	@MsHThong as int = -1,
	@LoaiBT as int = '-1',
	@NGUOI_LAP NVARCHAR(100)  = '-1',
	@NGUOI_GS NVARCHAR(100) = '-1',
	@NNHAN as int = '-1',
	@image IMAGE = null,
	@NNgu as INT = 0
AS
--@NGHIEMTHU = 0 chua ngiem thu TINH_TRANG_PBT  <3
--@NGHIEMTHU = 1 hoan thanh TINH_TRANG_PBT = 3
--@NGHIEMTHU = 2 ngiem thu TINH_TRANG_PBT > 3 34


SELECT * INTO #MAY FROM dbo.MGetMayUserNgay(@DENNGAY, @USERNAME, @MS_NHA_XUONG, @MsHThong, -1, @LOAY_MAY, @NHOM_MAY,@MS_MAY, @NNgu )


			
SELECT A.*,B.MS_HE_THONG,B.MS_LOAI_MAY,B.MS_NHOM_MAY,B.Ten_N_XUONG,B.MS_N_XUONG,B.TEN_MAY INTO #PBT FROM dbo.PHIEU_BAO_TRI A INNER JOIN #MAY B ON A.MS_MAY = B.MS_MAY
WHERE  CONVERT(DATETIME, CONVERT(NVARCHAR(10),NGAY_BD_KH,101)) BETWEEN CONVERT(DATETIME,CONVERT(NVARCHAR(10),@TUNGAY ,101)) AND CONVERT(DATETIME,@DENNGAY ,101)
				AND  ( ((@NGHIEMTHU = 0) AND TINH_TRANG_PBT < 3)  OR  ( (@NGHIEMTHU = 1) AND TINH_TRANG_PBT = 3 ) 
				OR  ( (@NGHIEMTHU = 2) AND TINH_TRANG_PBT > 3 ) )
				AND (@LoaiBT = '-1' OR MS_LOAI_BT = @LoaiBT)
				AND (NGUOI_LAP = @NGUOI_LAP OR @NGUOI_LAP = '-1')
				AND (NGUOI_GIAM_SAT = @NGUOI_GS OR @NGUOI_GS = '-1')
				AND (MS_NGUYEN_NHAN = @NNHAN OR @NNHAN = -1)	
								

SELECT MS_PHIEU_BAO_TRI,CONVERT(Image,@image) AS TAI_LIEU INTO #PHIEU_BAO_TRI_HINH FROM 
(SELECT DISTINCT MS_PHIEU_BAO_TRI FROM PHIEU_BAO_TRI_HINH T1) T2
				
SELECT T9.TAI_LIEU,
	T2.MS_HE_THONG AS MS_HT, MS_LOAI_MAY, MS_NHOM_MAY, T2.MS_PHIEU_BAO_TRI, T2.SO_PHIEU_BAO_TRI, T2.MS_MAY,
	TEN_MAY, TINH_TRANG_PBT,CASE @NNgu WHEN 0 THEN T4.TEN_TINH_TRANG WHEN 1 THEN T4.TEN_TINH_TRANG_ANH ELSE TEN_TIENG_HOA END AS TEN_TINH_TRANG,
	CONVERT(NVARCHAR(500),CASE @NNgu WHEN 0 THEN T8.TEN_TIENG_VIET WHEN 1 THEN T8.TEN_TIENG_ANH ELSE TEN_TIENG_HOA END) AS TEN_TIENG_VIET	
	, T2.MS_LOAI_BT, TEN_LOAI_BT, LY_DO_BT, NGAY_LAP, Ten_N_XUONG AS TEN_N_XUONG , 
	T2.MS_N_XUONG, Convert(nvarchar(4000),dbo.GetMS_YEU_CAU(T2.MS_PHIEU_BAO_TRI)) AS MS_YEU_CAU , GIO_LAP, T2.MS_UU_TIEN, TEN_UU_TIEN, NGUOI_LAP, USERNAME_NGUOI_LAP, HO + ' ' + TEN AS HO_TEN, 
	NGUOI_GIAM_SAT, NGAY_BD_KH, NGAY_KT_KH, GIO_HONG, NGAY_HONG, T2.MS_NGUYEN_NHAN, DEN_GIO_HONG, DEN_NGAY_HONG,DHX ,		
(SELECT TOP 1 GHI_CHU  FROM PHIEU_BAO_TRI_TINH_TRANG_CHI_TIET 
WHERE MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI
ORDER BY THOI_GIAN DESC) AS LY_DO_TT_PBT_CT,UPDATE_NGAY_CUOI, STT_CA,
CONVERT(BIT,CASE WHEN ISNULL(T10.MS_PBT,'0') = '0' THEN 0 ELSE 1 END) AS TGNM
FROM 
	#PBT AS T2 INNER JOIN
	TINH_TRANG_PBT T4 ON T2.TINH_TRANG_PBT = T4.STT LEFT JOIN      
	MUC_UU_TIEN T5 ON T2.MS_UU_TIEN = T5.MS_UU_TIEN INNER JOIN  
	LOAI_BAO_TRI T6 ON T2.MS_LOAI_BT = T6.MS_LOAI_BT INNER JOIN  
	CONG_NHAN T7 ON T2.NGUOI_LAP =  T7.MS_CONG_NHAN LEFT JOIN 
	TINH_TRANG_PBT_CT T8 ON T8.MS_TT_CT = T2.MS_TT_CT LEFT JOIN	
	#PHIEU_BAO_TRI_HINH T9 ON T9.MS_PHIEU_BAO_TRI = T2.MS_PHIEU_BAO_TRI LEFT JOIN 
	dbo.THOI_GIAN_DUNG_MAY T10 ON T2.MS_PHIEU_BAO_TRI = T10.MS_PBT

ORDER BY T2.MS_PHIEU_BAO_TRI DESC

GO
ALTER procedure [dbo].[MBDTGNgungMayTheoMay]
	@TNgay datetime,
	@DNgay datetime,
	@MS_TINH NVARCHAR(100),
	@MS_QUAN NVARCHAR(100),
	@MS_DUONG NVARCHAR(100),
	@MSNX NVARCHAR(150),
	@MSHT INT,
	@MSLMAY NVARCHAR(50),
	@MSNHOMMAY NVARCHAR(50)
as
-- @MS_TINH THAY THE USER
--@MS_QUAN THAY THE NGON NGU
SELECT A.MS_MAY, TEN_MAY AS TMAY , A.MS_N_XUONG INTO #MAY_TB FROM dbo.MGetMayUserNgay(@DNgay,@MS_TINH,@MSNX,@MSHT,-1,@MSLMAY,@MSNHOMMAY,'-1',@MS_QUAN) A
SELECT A.MS_MAY,TMAY, MS_NGUYEN_NHAN,SUM(THOI_GIAN_SUA_CHUA) AS THOI_GIAN_SUA_CHUA, 
		SUM(THOI_GIAN_SUA) AS THOI_GIAN_SUA -- , COUNT(DISTINCT MS_LAN) AS SO_LAN
FROM dbo.THOI_GIAN_DUNG_MAY A  INNER JOIN #MAY_TB B ON A.MS_MAY = B.MS_MAY 
WHERE A.NGAY_DUNG BETWEEN @TNgay AND @DNgay GROUP BY A.MS_MAY,TMAY,MS_NGUYEN_NHAN
GO
ALTER FUNCTION [dbo].[MGetTGNMay] ( 
	@TNgay DATETIME ,
	@DNgay DATETIME ,
	@MS_MAY NVARCHAR(30)
)

RETURNS float AS BEGIN

declare @TGian FLOAT

SELECT @TGian = ISNULL(SUM(THOI_GIAN_SUA_CHUA) / 60,0)  FROM dbo.THOI_GIAN_DUNG_MAY AS A INNER JOIN 
dbo.NGUYEN_NHAN_DUNG_MAY AS B ON A.MS_NGUYEN_NHAN = B.MS_NGUYEN_NHAN 
WHERE (MS_MAY = @MS_MAY)  AND (A.NGAY_DUNG BETWEEN @TNgay AND @DNgay ) 
AND  (B.HU_HONG = 1)  



RETURN @TGian
END
GO
ALTER FUNCTION [dbo].[MGetSLanNgungMay] ( 
	@TNgay DATETIME ,
	@DNgay DATETIME ,
	@MS_MAY NVARCHAR(30)
)

RETURNS INT AS BEGIN

declare @TGian INT

SELECT @TGian = ISNULL(COUNT(MS_LAN),0) FROM (SELECT DISTINCT (SUM(CASE ISNULL(ID_CHA,'') WHEN '' THEN 1 ELSE 0 END)) MS_LAN, MS_MAY
FROM dbo.THOI_GIAN_DUNG_MAY AS A 
LEFT JOIN NGUYEN_NHAN_DUNG_MAY B ON B.MS_NGUYEN_NHAN = A.MS_NGUYEN_NHAN
WHERE ISNULL(A.MS_NGUYEN_NHAN, 0) <> 0 AND B.HU_HONG = 1 AND
 (A.NGAY_DUNG BETWEEN @TNgay AND @DNgay) AND (MS_MAY = @MS_MAY)
 GROUP BY A.MS_MAY
 ) A 
RETURN @TGian
END
GO
ALTER FUNCTION [dbo].[MGetTGNMayAll]--kh�ng where HU_HONG
 ( 
	@TNgay DATETIME ,
	@DNgay DATETIME ,
	@MS_MAY NVARCHAR(30)
)

RETURNS float AS BEGIN

declare @TGian FLOAT

SELECT @TGian = ISNULL(SUM(THOI_GIAN_SUA_CHUA) / 60,0)  FROM dbo.THOI_GIAN_DUNG_MAY AS A INNER JOIN 
dbo.NGUYEN_NHAN_DUNG_MAY AS B ON A.MS_NGUYEN_NHAN = B.MS_NGUYEN_NHAN 
WHERE (MS_MAY = @MS_MAY)  AND (A.NGAY_DUNG BETWEEN @TNgay AND @DNgay ) 

RETURN @TGian
END
GO
ALTER procedure [dbo].[getMayTGNgungMay]	
	@UserName NVARCHAR(50),
	@MsNX NVARCHAR(50),
	@MsLoaiMay NVARCHAR(20),
	@MSHT INT,
	@TuNgay DATETIME,
	@DenNgay DATETIME,
	@NNgu int
AS


SELECT DISTINCT MS_MAY,TEN_MAY, A.Ten_N_XUONG, A.TEN_HE_THONG, A.TEN_LOAI_MAY INTO #MAY_USER FROM dbo.MGetMayUserNgay(
	@DenNgay,@UserName,@MsNX,@MSHT,-1,@MsLoaiMay,'-1','-1',0) A

SELECT DISTINCT CONVERT(BIT, 0) AS CHON, A.MS_MAY, A.TEN_MAY, A.Ten_N_XUONG, A.TEN_HE_THONG, A.TEN_LOAI_MAY
FROM         #MAY_USER A INNER JOIN                      
                      dbo.THOI_GIAN_DUNG_MAY  B ON A.MS_MAY = B.MS_MAY
WHERE     (B.NGAY_DUNG BETWEEN @TuNgay AND @DenNgay )
ORDER BY MS_MAY
GO
GO
ALTER procedure [dbo].[H_GET_DATA_HIEU_SUAT_SU_DUNG_MAY] 
	@NAM DATETIME = '01/01/2023',
	@MS_N_XUONG NVARCHAR(50) ='-1',
	@MS_LOAI_MAY NVARCHAR(20) ='-1'
AS

/*
DECLARE @NAM DATETIME
DECLARE @MS_N_XUONG NVARCHAR(50)
DECLARE @MS_LOAI_MAY INT

SET @NAM = '01/01/2009'
SET @MS_N_XUONG = 'NX003'
SET @MS_LOAI_MAY = -1
*/

IF @MS_N_XUONG <>'-1' AND @MS_LOAI_MAY = '-1' 
BEGIN
	SELECT KQ.MS_MAY,KQ.MS_NGUYEN_NHAN,KQ.BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE,
	SUM (LUYKE) AS LUYKE , KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY
	FROM 
	(
	SELECT TMP1.* , (TMP1.JAN +TMP1.FEB +TMP1.MAR +TMP1.APR  +TMP1.MAY +TMP1.JUN+ TMP1.JUL+ TMP1.AUG +TMP1.SEP +TMP1.OCT +TMP1.NOV+ TMP1.DECE)AS LUYKE,
	dbo.MAY.TEN_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN , dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM(
	SELECT MS_MAY,MS_NGUYEN_NHAN,BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE
	FROM 
	(
	SELECT     dbo.THOI_GIAN_DUNG_MAY.MS_MAY, dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG AS NGAY, dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,
		   	'JAN' = case when 1 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end, 
			'FEB' = case when 2 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAR' = case when 3 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'APR' = case when 4 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAY' = case when 5 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUN' = case when 6 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUL' = case when 7 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'AUG' = case when 8 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'SEP' = case when 9 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'OCT' = case when 10 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'NOV' = case when 11 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'DECE' = case when 12 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end 			
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	INNER JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY ON 
	                     dbo.THOI_GIAN_DUNG_MAY.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN 
				INNER JOIN
	                      dbo.MAY ON dbo.THOI_GIAN_DUNG_MAY.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) AND  dbo.THOI_GIAN_DUNG_MAY.MS_N_XUONG = @MS_N_XUONG
	)TMP
	GROUP BY MS_MAY ,MS_NGUYEN_NHAN,BTDK
	)TMP1 INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY ON 
	  TMP1.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN INNER JOIN
	  dbo.MAY ON TMP1.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	UNION 
	
	SELECT  dbo.MAY.MS_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,dbo.NGUYEN_NHAN_DUNG_MAY.BTDK,  0 AS JAN,0 AS FEB,0 AS  MAR, 0 AS  APR,0 AS MAY,0 AS  JUN,0 AS JUL,0 AS  AUG,0 AS SEP,0 AS OCT ,0 AS NOV,0 AS  DECE ,0 AS LUYKE ,dbo.MAY.TEN_MAY, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN, dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
	                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY CROSS JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY
	)KQ 
	WHERE KQ.MS_MAY IN (SELECT   DISTINCT  MS_MAY
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) AND  dbo.THOI_GIAN_DUNG_MAY.MS_N_XUONG = @MS_N_XUONG)
	GROUP BY KQ.MS_MAY,KQ.MS_NGUYEN_NHAN, KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN ,BTDK, KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY
	ORDER BY KQ.MS_MAY

END
ELSE IF @MS_N_XUONG <>'-1' AND @MS_LOAI_MAY <> '-1 '
BEGIN
	SELECT KQ.MS_MAY,KQ.MS_NGUYEN_NHAN, KQ.BTDK,SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE,
	SUM (LUYKE) AS LUYKE , KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY
	FROM 
	(
	SELECT TMP1.* , (TMP1.JAN +TMP1.FEB +TMP1.MAR +TMP1.APR  +TMP1.MAY +TMP1.JUN+ TMP1.JUL+ TMP1.AUG +TMP1.SEP +TMP1.OCT +TMP1.NOV+ TMP1.DECE)AS LUYKE,
	dbo.MAY.TEN_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN , dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM(
	SELECT MS_MAY,MS_NGUYEN_NHAN,BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE
	FROM 
	(
	SELECT     dbo.THOI_GIAN_DUNG_MAY.MS_MAY, dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG, dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,
		   	'JAN' = case when 1 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end, 
			'FEB' = case when 2 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAR' = case when 3 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'APR' = case when 4 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAY' = case when 5 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUN' = case when 6 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUL' = case when 7 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'AUG' = case when 8 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'SEP' = case when 9 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'OCT' = case when 10 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'NOV' = case when 11 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'DECE' = case when 12 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end 			
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	INNER JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY ON 
	                     dbo.THOI_GIAN_DUNG_MAY.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN 
				INNER JOIN
	                      dbo.MAY ON dbo.THOI_GIAN_DUNG_MAY.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) AND  dbo.THOI_GIAN_DUNG_MAY.MS_N_XUONG = @MS_N_XUONG
	AND dbo.LOAI_MAY.MS_LOAI_MAY = @MS_LOAI_MAY
	)TMP
	GROUP BY MS_MAY , MS_NGUYEN_NHAN,BTDK
	)TMP1 INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY ON 
	  TMP1.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN INNER JOIN
	  dbo.MAY ON TMP1.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	UNION 
	
	SELECT  dbo.MAY.MS_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,  0 AS JAN,0 AS FEB,0 AS  MAR, 0 AS  APR,0 AS MAY,0 AS  JUN,0 AS JUL,0 AS  AUG,0 AS SEP,0 AS OCT ,0 AS NOV,0 AS  DECE ,0 AS LUYKE ,dbo.MAY.TEN_MAY, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN, dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
	                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY CROSS JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY
	)KQ 
	WHERE KQ.MS_MAY IN (SELECT   DISTINCT  MS_MAY
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) AND  dbo.THOI_GIAN_DUNG_MAY.MS_N_XUONG = @MS_N_XUONG ) AND MS_LOAI_MAY = @MS_LOAI_MAY
	GROUP BY KQ.MS_MAY,KQ.MS_NGUYEN_NHAN, KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY,KQ.BTDK
	
	ORDER BY KQ.MS_MAY
END
ELSE IF @MS_N_XUONG = '-1' AND @MS_LOAI_MAY <> '-1' 
BEGIN 

SELECT KQ.MS_MAY,KQ.MS_NGUYEN_NHAN,KQ.BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE,
	SUM (LUYKE) AS LUYKE , KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY
	FROM 
	(
	SELECT TMP1.* , (TMP1.JAN +TMP1.FEB +TMP1.MAR +TMP1.APR  +TMP1.MAY +TMP1.JUN+ TMP1.JUL+ TMP1.AUG +TMP1.SEP +TMP1.OCT +TMP1.NOV+ TMP1.DECE)AS LUYKE,
	dbo.MAY.TEN_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN , dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM(
	SELECT MS_MAY,MS_NGUYEN_NHAN,BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE
	FROM 
	(
	SELECT     dbo.THOI_GIAN_DUNG_MAY.MS_MAY, dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG, dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,
		   	'JAN' = case when 1 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end, 
			'FEB' = case when 2 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAR' = case when 3 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'APR' = case when 4 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAY' = case when 5 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUN' = case when 6 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUL' = case when 7 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'AUG' = case when 8 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'SEP' = case when 9 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'OCT' = case when 10 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'NOV' = case when 11 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'DECE' = case when 12 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end 			
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	INNER JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY ON 
	                     dbo.THOI_GIAN_DUNG_MAY.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN 
				INNER JOIN
	                      dbo.MAY ON dbo.THOI_GIAN_DUNG_MAY.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM)
	AND dbo.LOAI_MAY.MS_LOAI_MAY = @MS_LOAI_MAY
	)TMP
	GROUP BY MS_MAY , MS_NGUYEN_NHAN,BTDK
	)TMP1 INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY ON 
	  TMP1.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN INNER JOIN
	  dbo.MAY ON TMP1.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	UNION 
	
	SELECT  dbo.MAY.MS_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK, 0 AS JAN,0 AS FEB,0 AS  MAR, 0 AS  APR,0 AS MAY,0 AS  JUN,0 AS JUL,0 AS  AUG,0 AS SEP,0 AS OCT ,0 AS NOV,0 AS  DECE ,0 AS LUYKE ,dbo.MAY.TEN_MAY, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN, dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
	                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY CROSS JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY
	)KQ 
	WHERE KQ.MS_MAY IN (SELECT   DISTINCT  MS_MAY
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) ) AND MS_LOAI_MAY = @MS_LOAI_MAY
	GROUP BY KQ.MS_MAY,KQ.MS_NGUYEN_NHAN, KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY,KQ.BTDK
	ORDER BY KQ.MS_MAY

END
ELSE IF @MS_N_XUONG ='-1' AND @MS_LOAI_MAY = '-1' 
BEGIN


SELECT KQ.MS_MAY,KQ.MS_NGUYEN_NHAN,KQ.BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE,
	SUM (LUYKE) AS LUYKE , KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY
	FROM 
	(
	SELECT TMP1.* , (TMP1.JAN +TMP1.FEB +TMP1.MAR +TMP1.APR  +TMP1.MAY +TMP1.JUN+ TMP1.JUL+ TMP1.AUG +TMP1.SEP +TMP1.OCT +TMP1.NOV+ TMP1.DECE)AS LUYKE,
	dbo.MAY.TEN_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN , dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM(
	SELECT MS_MAY,MS_NGUYEN_NHAN,BTDK, SUM(JAN)AS JAN,SUM(FEB)AS FEB, SUM(MAR)AS MAR, SUM(APR)AS APR, SUM(MAY)AS MAY, SUM(JUN)AS JUN, SUM(JUL) AS JUL, SUM(AUG) AS AUG,SUM(SEP) AS SEP,SUM(OCT) AS OCT , SUM(NOV) AS NOV, SUM(DECE) AS DECE
	FROM 
	(
	SELECT     dbo.THOI_GIAN_DUNG_MAY.MS_MAY, dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG, dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,
		   	'JAN' = case when 1 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end, 
			'FEB' = case when 2 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAR' = case when 3 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'APR' = case when 4 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'MAY' = case when 5 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUN' = case when 6 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'JUL' = case when 7 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'AUG' = case when 8 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'SEP' = case when 9 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'OCT' = case when 10 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'NOV' = case when 11 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end ,
			'DECE' = case when 12 = DATEPART(MONTH,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) then dbo.THOI_GIAN_DUNG_MAY.THOI_GIAN_SUA_CHUA else 0 end 			
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	INNER JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY ON 
	                     dbo.THOI_GIAN_DUNG_MAY.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN 
				INNER JOIN
	                      dbo.MAY ON dbo.THOI_GIAN_DUNG_MAY.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM)
	
	)TMP
	GROUP BY MS_MAY , MS_NGUYEN_NHAN,BTDK
	)TMP1 INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY ON 
	  TMP1.MS_NGUYEN_NHAN = dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN INNER JOIN
	  dbo.MAY ON TMP1.MS_MAY = dbo.MAY.MS_MAY INNER JOIN
	                      dbo.NHOM_MAY ON dbo.MAY.MS_NHOM_MAY = dbo.NHOM_MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY
	UNION 
	
	SELECT  dbo.MAY.MS_MAY, dbo.NGUYEN_NHAN_DUNG_MAY.MS_NGUYEN_NHAN,BTDK,  0 AS JAN,0 AS FEB,0 AS  MAR, 0 AS  APR,0 AS MAY,0 AS  JUN,0 AS JUL,0 AS  AUG,0 AS SEP,0 AS OCT ,0 AS NOV,0 AS  DECE ,0 AS LUYKE ,dbo.MAY.TEN_MAY, 
	                      dbo.NGUYEN_NHAN_DUNG_MAY.TEN_NGUYEN_NHAN, dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
	                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
	                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY CROSS JOIN
	                      dbo.NGUYEN_NHAN_DUNG_MAY
	)KQ 
	WHERE KQ.MS_MAY IN (SELECT   DISTINCT  MS_MAY
	FROM         dbo.THOI_GIAN_DUNG_MAY 
	WHERE DATEPART(year,dbo.THOI_GIAN_DUNG_MAY.NGAY_DUNG) = DATEPART(year,@NAM) )
	GROUP BY KQ.MS_MAY,KQ.MS_NGUYEN_NHAN, KQ.TEN_MAY, KQ.TEN_NGUYEN_NHAN , KQ.MS_LOAI_MAY, KQ.TEN_LOAI_MAY,BTDK
	ORDER BY KQ.MS_MAY

END
GO
ALTER procedure [dbo].[H_GET_NAM_THOI_GIAN_NGUNG_MAY] 
AS
SELECT DISTINCT TOP 100 PERCENT DATEPART([year], NGAY_DUNG) AS NAM
FROM         dbo.THOI_GIAN_DUNG_MAY
ORDER BY DATEPART([year], NGAY_DUNG) DESC
GO
ALTER procedure [dbo].[H_GET_LOAI_MAY_NX_TGNM] 
    @MS_N_XUONG NVARCHAR(50)
AS
IF @MS_N_XUONG = '-1'
BEGIN
	SELECT DISTINCT  dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY INNER JOIN
                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
                      dbo.THOI_GIAN_DUNG_MAY ON dbo.MAY.MS_MAY = dbo.THOI_GIAN_DUNG_MAY.MS_MAY
END
ELSE
BEGIN
	SELECT DISTINCT  dbo.LOAI_MAY.MS_LOAI_MAY, dbo.LOAI_MAY.TEN_LOAI_MAY
	FROM         dbo.NHOM_MAY INNER JOIN
                      dbo.LOAI_MAY ON dbo.NHOM_MAY.MS_LOAI_MAY = dbo.LOAI_MAY.MS_LOAI_MAY INNER JOIN
                      dbo.MAY ON dbo.NHOM_MAY.MS_NHOM_MAY = dbo.MAY.MS_NHOM_MAY INNER JOIN
                      dbo.THOI_GIAN_DUNG_MAY ON dbo.MAY.MS_MAY = dbo.THOI_GIAN_DUNG_MAY.MS_MAY
	WHERE dbo.THOI_GIAN_DUNG_MAY.MS_N_XUONG = @MS_N_XUONG
END


