IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetDowtimeCause')
   exec('CREATE PROCEDURE spGetDowtimeCause AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROCEDURE spGetDowtimeCause
	@NNgu INT =0 
AS	
BEGIN
	SELECT B.TEN_NGUYEN_NHAN AS name,SUM(A.THOI_GIAN_SUA_CHUA) AS y FROM dbo.THOI_GIAN_DUNG_MAY A
	INNER JOIN dbo.NGUYEN_NHAN_DUNG_MAY B ON B.MS_NGUYEN_NHAN = A.MS_NGUYEN_NHAN
	WHERE CONVERT(DATE,A.NGAY_DUNG) BETWEEN CONVERT(DATE,DATEADD(MONTH,-6,GETDATE())) AND CONVERT(DATE,GETDATE())
	GROUP BY B.TEN_NGUYEN_NHAN
END
GO


