
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListDownTimeByDate')
   exec('CREATE PROCEDURE spGetListDownTimeByDate AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListDownTimeByDate
	@USERNAME NVARCHAR(250) ='admin',
	@NNgu INT = 0,
	@LOAI_MAY NVARCHAR(30) = '-1',
	@MS_HETHONG NVARCHAR(30) = -1,
	@MS_NHA_XUONG NVARCHAR(30) = '-1',
	@TuNgay DATE = '10/19/2020',
	@DenNgay DATE  ='12/25/2021',
	@LOCK BIT
AS
BEGIN
	
	SELECT DISTINCT * INTO #MAY_USER FROM dbo.MGetMayUserNgay(@DenNgay,@USERNAME,@MS_NHA_XUONG,@MS_HETHONG,-1,@LOAI_MAY,'-1','-1',@NNgu)  A 
	SELECT DISTINCT TGDM.MS_MAY, CAST(TGDM.NGAY_DUNG AS DATE) AS NGAY
	FROM dbo.THOI_GIAN_DUNG_MAY TGDM
	INNER JOIN #MAY_USER MAY ON MAY.MS_MAY = TGDM.MS_MAY
	WHERE CAST(TGDM.NGAY_DUNG AS DATE) BETWEEN @TuNgay AND @DenNgay 
	--AND ISNULL(TGDM.CLOSED,0) =@LOCK
	ORDER BY NGAY DESC, TGDM.MS_MAY
END	

GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListDownTime')
   exec('CREATE PROCEDURE spGetListDownTime AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetListDownTime]
	@USERNAME NVARCHAR(250) ='admin',
	@NNgu INT = 0,
	@MS_MAY NVARCHAR(30) = '-1',
	@NGAY DATE = '2022/05/24'
AS 
BEGIN
	SELECT TGDM.ID, TGDM.MS_MAY, TGDM.CaID,
	TGDM.NGAY_DUNG AS NGAY, TGDM.TU_GIO AS  TU_GIO,TGDM.DEN_GIO  AS  DEN_NGAY,TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA AS THOI_GIAN_NGUNG_MAY, TGDM.THOI_GIAN_SUA_CHUA, DTT.ID_DownTime AS ID_DownType,
	TGDM.MS_NGUYEN_NHAN,TGDM.HIEN_TUONG, TGDM.NGUYEN_NHAN_CU_THE, TGDM.GHI_CHU,TGDM.NGUOI_GIAI_QUYET,TGDM.TRUONG_CA, TGDM.ID_CHA,TGDM.MS_TO,TGDM.MS_PBT AS  MS_PHIEU_BAO_TRI
	FROM dbo.THOI_GIAN_DUNG_MAY TGDM
	LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
	LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
	LEFT JOIN dbo.DownTimeType DTT ON DTT.ID_DownTime = NNDM.DownTimeTypeID
	WHERE (TGDM.MS_MAY = @MS_MAY OR @MS_MAY = '-1') AND CAST(TGDM.NGAY_DUNG AS DATE) = @NGAY
	ORDER BY TGDM.MS_MAY, TGDM.TU_GIO, TGDM.DEN_GIO, CA

	

END	
GO

IF EXISTS (SELECT *
           FROM   sys.objects
           WHERE  object_id = OBJECT_ID(N'[dbo].[fnGetNguyenNhanNM]')
                  AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT' ))
  DROP FUNCTION [dbo].[fnGetNguyenNhanNM]
GO 
CREATE FUNCTION [dbo].[fnGetNguyenNhanNM]
(
	@IDNM BIGINT
)
returns @TGNM TABLE (MS_NM BIGINT)
as
begin	
	DECLARE @ID_TEMP BIGINT = @IDNM
	WHILE (SELECT COUNT(*) FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID_TEMP) > 0
	BEGIN
		INSERT INTO @TGNM( MS_NM)
		SELECT TGDM.ID FROM dbo.THOI_GIAN_DUNG_MAY TGDM
		WHERE ID = @ID_TEMP
		SET @ID_TEMP = (SELECT TOP 1 ID_CHA FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID_TEMP)
	END
	SET @ID_TEMP = @IDNM
	WHILE (SELECT COUNT(*) FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @ID_TEMP) > 0
	BEGIN
		INSERT INTO @TGNM(MS_NM)
		SELECT TOP 1 TGDM.ID FROM dbo.THOI_GIAN_DUNG_MAY TGDM
		WHERE ID_CHA = @ID_TEMP
		SET @ID_TEMP = (SELECT TOP 1 ID FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @ID_TEMP)
	END
return 
end
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spSaveThoiGianNgungMay')
   exec('CREATE PROCEDURE spSaveThoiGianNgungMay AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spSaveThoiGianNgungMay
	@USERNAME NVARCHAR(250) ='admin',
    @ID BIGINT,
	@ID_CHA BIGINT,
    @MS_MAY NVARCHAR(30) ,
    @MS_NGUYEN_NHAN INT ,
	@NGUYEN_NHAN NVARCHAR(250),
	@NGUYEN_NHAN_CU_THE NVARCHAR(250),
	@HIEN_TUONG NVARCHAR(250),
	@GHI_CHU NVARCHAR(500),
	@TRUONG_CA NVARCHAR(250),
	@NGUOI_GIAI_QUYET NVARCHAR(250),
	@MS_PHIEU_BAO_TRI NVARCHAR(250),
	@MS_TO INT,
	@THOI_GIAN_SUA FLOAT,
	@THOI_GIAN_SUA_CHUA FLOAT,
	@sBTNgay NVARCHAR(250)
AS
    BEGIN
		CREATE TABLE #TEMPT_TG (
		[NGAY] [datetime] NULL,
		[TU_GIO] [datetime] NULL,
		[DEN_NGAY] [datetime] NULL,
		[DEN_GIO] [datetime] NULL,
		[CaID] [int] NULL
		) ON [PRIMARY]
	

		DECLARE @sSql nvarchar(4000)
		set @sSql = 'INSERT INTO #TEMPT_TG(NGAY,TU_GIO,DEN_NGAY,DEN_GIO,CaID)SELECT NGAY,TU_GIO,DEN_NGAY,DEN_GIO,CaID FROM '+ @sBTNgay
		EXEC (@sSql)
		--set @sSql = 'DROP TABLE ' + @sBTNgay
		--EXEC (@sSql)

		
		  IF @ID = -1
		  BEGIN
			
			IF @ID = -1
			DECLARE @ngay DATETIME
			WHILE((SELECT COUNT(*) FROM #TEMPT_TG) > 0)
			BEGIN
				SELECT  @ngay = (SELECT MIN (CONVERT(DATETIME,CONVERT(NVARCHAR(10),NGAY,101) + ' ' + CONVERT(NVARCHAR(10),TU_GIO,108)))) FROM #TEMPT_TG
				DECLARE @MS_CHA BIGINT;
				SET @MS_CHA = CASE WHEN @ID_CHA > 0 THEN @ID_CHA else (SELECT TOP 1 ID FROM dbo.THOI_GIAN_DUNG_MAY WHERE (DEN_GIO = @ngay) AND  MS_MAY =@MS_MAY) END

				INSERT INTO dbo.THOI_GIAN_DUNG_MAY(MS_MAY,CaID,NGAY_DUNG,TU_GIO,DEN_GIO,THOI_GIAN_SUA_CHUA,THOI_GIAN_SUA,MS_NGUYEN_NHAN,MS_NGUYEN_NHAN_GOC,USERNAME,ID_CHA,MS_HE_THONG,MS_PBT,
				GHI_CHU,UserEdit,DateEdit,TRUONG_CA,NGUOI_GIAI_QUYET,MS_N_XUONG,MS_TO,HIEN_TUONG,NGUYEN_NHAN_CU_THE)				
			
				SELECT @MS_MAY,CaID,NGAY,(CONVERT(DATETIME,CONVERT(NVARCHAR(10),NGAY,101) + ' ' + CONVERT(NVARCHAR(10),TU_GIO,108))),(CONVERT(DATETIME,CONVERT(NVARCHAR(10),DEN_NGAY,101) + ' ' + CONVERT(NVARCHAR(10),DEN_GIO,108))),DATEDIFF(MINUTE,NGAY+CONVERT(NVARCHAR(20),TU_GIO,114),DEN_NGAY+CONVERT(NVARCHAR(20),DEN_GIO,114)),DATEDIFF(MINUTE,NGAY+CONVERT(NVARCHAR(20),TU_GIO,114),DEN_NGAY+CONVERT(NVARCHAR(20),DEN_GIO,114)),
				@MS_NGUYEN_NHAN,@MS_NGUYEN_NHAN,@USERNAME,@MS_CHA,(SELECT MS_HE_THONG FROM dbo.MAY_HE_THONG WHERE MS_MAY =@MS_MAY),@MS_PHIEU_BAO_TRI,@GHI_CHU,@USERNAME,GETDATE(),@TRUONG_CA,@NGUOI_GIAI_QUYET
				,(SELECT MS_N_XUONG FROM dbo.MAY_NHA_XUONG WHERE MS_MAY =@MS_MAY),@MS_TO,@HIEN_TUONG,@NGUYEN_NHAN_CU_THE FROM #TEMPT_TG WHERE  NGAY + CONVERT(NVARCHAR(20),TU_GIO,114) = @ngay
				DELETE #TEMPT_TG WHERE  (CONVERT(DATETIME,CONVERT(NVARCHAR(10),NGAY,101) + ' ' + CONVERT(NVARCHAR(10),TU_GIO,108)))  = @ngay
				END
				SET @ID = SCOPE_IDENTITY()
			END
			ELSE

			BEGIN
				--lấy tất cả các nguyên nhân có liên quan

				 UPDATE dbo.THOI_GIAN_DUNG_MAY
				 SET MS_NGUYEN_NHAN =@MS_NGUYEN_NHAN,
				 TRUONG_CA =@TRUONG_CA,
				 GHI_CHU =@GHI_CHU,
				 NGUOI_GIAI_QUYET =@NGUOI_GIAI_QUYET,
				 NGUYEN_NHAN_CU_THE =@NGUYEN_NHAN_CU_THE,
				 HIEN_TUONG = @HIEN_TUONG,
				 MS_PBT =@MS_PHIEU_BAO_TRI,
				 MS_TO =@MS_TO
				 WHERE ID IN(SELECT * FROM dbo.fnGetNguyenNhanNM(@ID))


				 UPDATE dbo.THOI_GIAN_DUNG_MAY SET
				 NGAY_DUNG = (SELECT TOP 1 NGAY FROM #TEMPT_TG),
				 TU_GIO = (SELECT TOP 1 (CONVERT(DATETIME,CONVERT(NVARCHAR(10),NGAY,101) + ' ' + CONVERT(NVARCHAR(10),TU_GIO,108))) FROM #TEMPT_TG),
				 DEN_GIO = (SELECT TOP 1 (CONVERT(DATETIME,CONVERT(NVARCHAR(10),DEN_NGAY,101) + ' ' + CONVERT(NVARCHAR(10),DEN_GIO,108))) FROM #TEMPT_TG),
				 THOI_GIAN_SUA = @THOI_GIAN_SUA,
				 THOI_GIAN_SUA_CHUA =@THOI_GIAN_SUA_CHUA
				 WHERE ID = @ID

				 --insert vào những thèn nào chưa tồn tại
			END
			SELECT @ID
    END
	

go
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListTGianNMayView')
   exec('CREATE PROCEDURE spGetListTGianNMayView AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListTGianNMayView
	@NNgu INT = 0,
	@ID BIGINT = NULL
AS 
BEGIN
	
	---lấy kiểm tra msPBT khác null hay không

	SELECT TGDM.ID, TGDM.MS_MAY, CASE @NNgu WHEN 0 THEN CA.CA WHEN 1 THEN ISNULL(NULLIF(CA.CA_ANH, ''), CA.CA) ELSE ISNULL(NULLIF(CA.CA_HOA, ''), CA.CA) END AS CA ,TGDM.TU_GIO, TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA_CHUA, TGDM.THOI_GIAN_SUA, CASE @NNgu WHEN 0 THEN DT.DownTimeTypeName WHEN 1 THEN ISNULL(NULLIF(DT.DownTimeTypeNameA, ''), DT.DownTimeTypeName) ELSE ISNULL(NULLIF(DT.DownTimeTypeNameH, ''), DT.DownTimeTypeName) END AS DownTimeTypeName, CASE @NNgu WHEN 1 THEN ISNULL(NULLIF(NNDM.TEN_NGUYEN_NHAN_ANH, ''), NNDM.TEN_NGUYEN_NHAN) ELSE NNDM.TEN_NGUYEN_NHAN END AS TEN_NGUYEN_NHAN, TGDM.NGUYEN_NHAN_CU_THE AS NGUYEN_NHAN, TGDM.HIEN_TUONG 
	INTO #BT_TGDM
	FROM dbo.THOI_GIAN_DUNG_MAY TGDM
	LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
	LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
	LEFT JOIN dbo.DownTimeType DT ON DT.ID_DownTime = NNDM.DownTimeTypeID
	WHERE 1 = 0

	DECLARE @MS_PBT NVARCHAR(50) = (SELECT TOP 1 ISNULL(MS_PBT,'') FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID)

	IF(@MS_PBT = '')
	BEGIN
	DECLARE @ID_TEMP BIGINT = @ID
	WHILE (SELECT COUNT(*) FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID_TEMP) > 0
	BEGIN
		INSERT INTO #BT_TGDM(ID, MS_MAY, CA,TU_GIO, DEN_GIO, THOI_GIAN_SUA_CHUA, THOI_GIAN_SUA, DownTimeTypeName, TEN_NGUYEN_NHAN, NGUYEN_NHAN, HIEN_TUONG)
		SELECT TGDM.ID, TGDM.MS_MAY, CASE @NNgu WHEN 0 THEN CA.CA WHEN 1 THEN ISNULL(NULLIF(CA.CA_ANH, ''), CA.CA) ELSE ISNULL(NULLIF(CA.CA_HOA, ''), CA.CA) END AS CA,TGDM.TU_GIO, TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA_CHUA, TGDM.THOI_GIAN_SUA, CASE @NNgu WHEN 0 THEN DT.DownTimeTypeName WHEN 1 THEN ISNULL(NULLIF(DT.DownTimeTypeNameA, ''), DT.DownTimeTypeName) ELSE ISNULL(NULLIF(DT.DownTimeTypeNameH, ''), DT.DownTimeTypeName) END AS DownTimeTypeName, CASE @NNgu WHEN 1 THEN ISNULL(NULLIF(NNDM.TEN_NGUYEN_NHAN_ANH, ''), NNDM.TEN_NGUYEN_NHAN) ELSE NNDM.TEN_NGUYEN_NHAN END AS TEN_NGUYEN_NHAN,TGDM.NGUYEN_NHAN_CU_THE AS NGUYEN_NHAN, TGDM.HIEN_TUONG 
		FROM dbo.THOI_GIAN_DUNG_MAY TGDM
		LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
		LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
		LEFT JOIN dbo.DownTimeType DT ON DT.ID_DownTime = NNDM.DownTimeTypeID
		WHERE ID = @ID_TEMP

		SET @ID_TEMP = (SELECT TOP 1 ID_CHA FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID_TEMP)
	END

	SET @ID_TEMP = @ID 
	WHILE (SELECT COUNT(*) FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @ID_TEMP) > 0
	BEGIN
		INSERT INTO #BT_TGDM(ID, MS_MAY, CA,TU_GIO, DEN_GIO, THOI_GIAN_SUA_CHUA, THOI_GIAN_SUA, DownTimeTypeName, TEN_NGUYEN_NHAN, NGUYEN_NHAN, HIEN_TUONG)
		SELECT TGDM.ID, TGDM.MS_MAY, CASE @NNgu WHEN 0 THEN CA.CA WHEN 1 THEN ISNULL(NULLIF(CA.CA_ANH, ''), CA.CA) ELSE ISNULL(NULLIF(CA.CA_HOA, ''), CA.CA) END AS CA,TGDM.TU_GIO, TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA_CHUA, TGDM.THOI_GIAN_SUA, CASE @NNgu WHEN 0 THEN DT.DownTimeTypeName WHEN 1 THEN ISNULL(NULLIF(DT.DownTimeTypeNameA, ''), DT.DownTimeTypeName) ELSE ISNULL(NULLIF(DT.DownTimeTypeNameH, ''), DT.DownTimeTypeName) END AS DownTimeTypeName, CASE @NNgu WHEN 1 THEN ISNULL(NULLIF(NNDM.TEN_NGUYEN_NHAN_ANH, ''), NNDM.TEN_NGUYEN_NHAN) ELSE NNDM.TEN_NGUYEN_NHAN END AS TEN_NGUYEN_NHAN, TGDM.NGUYEN_NHAN_CU_THE  AS  NGUYEN_NHAN, TGDM.HIEN_TUONG 
		FROM dbo.THOI_GIAN_DUNG_MAY TGDM
		LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
		LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
		LEFT JOIN dbo.DownTimeType DT ON DT.ID_DownTime = NNDM.DownTimeTypeID
		WHERE ID_CHA = @ID_TEMP
		SET @ID_TEMP = (SELECT TOP 1 ID FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @ID_TEMP)
	END

	END
	ELSE
    BEGIN
		INSERT INTO #BT_TGDM(ID, MS_MAY, CA,TU_GIO, DEN_GIO, THOI_GIAN_SUA_CHUA, THOI_GIAN_SUA, DownTimeTypeName, TEN_NGUYEN_NHAN, NGUYEN_NHAN, HIEN_TUONG)
		SELECT TGDM.ID, TGDM.MS_MAY, CASE @NNgu WHEN 0 THEN CA.CA WHEN 1 THEN ISNULL(NULLIF(CA.CA_ANH, ''), CA.CA) ELSE ISNULL(NULLIF(CA.CA_HOA, ''), CA.CA) END AS CA,TGDM.TU_GIO, TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA_CHUA, TGDM.THOI_GIAN_SUA, CASE @NNgu WHEN 0 THEN DT.DownTimeTypeName WHEN 1 THEN ISNULL(NULLIF(DT.DownTimeTypeNameA, ''), DT.DownTimeTypeName) ELSE ISNULL(NULLIF(DT.DownTimeTypeNameH, ''), DT.DownTimeTypeName) END AS DownTimeTypeName, CASE @NNgu WHEN 1 THEN ISNULL(NULLIF(NNDM.TEN_NGUYEN_NHAN_ANH, ''), NNDM.TEN_NGUYEN_NHAN) ELSE NNDM.TEN_NGUYEN_NHAN END AS TEN_NGUYEN_NHAN, TGDM.NGUYEN_NHAN_CU_THE  AS  NGUYEN_NHAN, TGDM.HIEN_TUONG 
		FROM dbo.THOI_GIAN_DUNG_MAY TGDM
		LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
		LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
		LEFT JOIN dbo.DownTimeType DT ON DT.ID_DownTime = NNDM.DownTimeTypeID
		WHERE TGDM.MS_PBT = @MS_PBT
	END

	SELECT ID, MS_MAY, CA,TU_GIO, DEN_GIO, THOI_GIAN_SUA_CHUA, THOI_GIAN_SUA, DownTimeTypeName, TEN_NGUYEN_NHAN FROM #BT_TGDM ORDER BY TU_GIO
	DELETE #BT_TGDM
END	
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListChooseTGianNMay')
   exec('CREATE PROCEDURE spGetListChooseTGianNMay AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListChooseTGianNMay
	@NNgu INT = 0,
	@ID BIGINT = 561,
	@ID_CHA BIGINT = 0,
	@TGio DATETIME = '01/18/2023',
	@DGio DATETIME = '05/20/2024'
AS 
BEGIN
	
	SELECT CONVERT(BIT, 0)  AS CHON, TGDM.ID, TGDM.MS_MAY, CASE @NNgu WHEN 0 THEN CA.CA WHEN 1 THEN ISNULL(NULLIF(CA.CA_ANH, ''), CA.CA) ELSE ISNULL(NULLIF(CA.CA_HOA, ''), CA.CA) END AS CA ,TGDM.TU_GIO, TGDM.DEN_GIO, TGDM.THOI_GIAN_SUA_CHUA, TGDM.THOI_GIAN_SUA, CASE @NNgu WHEN 0 THEN DT.DownTimeTypeName WHEN 1 THEN ISNULL(NULLIF(DT.DownTimeTypeNameA, ''), DT.DownTimeTypeName) ELSE ISNULL(NULLIF(DT.DownTimeTypeNameH, ''), DT.DownTimeTypeName) END AS DownTimeTypeName, CASE @NNgu WHEN 1 THEN ISNULL(NULLIF(NNDM.TEN_NGUYEN_NHAN_ANH, ''), NNDM.TEN_NGUYEN_NHAN) ELSE NNDM.TEN_NGUYEN_NHAN END AS TEN_NGUYEN_NHAN, TGDM.HIEN_TUONG 
	FROM dbo.THOI_GIAN_DUNG_MAY TGDM
	LEFT JOIN dbo.CA CA ON CA.STT = TGDM.CaID
	LEFT JOIN dbo.NGUYEN_NHAN_DUNG_MAY NNDM ON NNDM.MS_NGUYEN_NHAN = TGDM.MS_NGUYEN_NHAN
	LEFT JOIN dbo.DownTimeType DT ON DT.ID_DownTime = NNDM.DownTimeTypeID
	WHERE (CONVERT(DATE, TGDM.TU_GIO) BETWEEN CONVERT(DATE, @TGio) AND CONVERT(DATE, @DGio)) AND TGDM.ID <> @ID AND TGDM.MS_MAY = (SELECT TOP 1 MS_MAY FROM  dbo.THOI_GIAN_DUNG_MAY WHERE ID = @ID) AND ((SELECT COUNT(ID) FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = TGDM.ID) = 0)
	UNION
	SELECT CONVERT(BIT, 0) AS CHON, NULL AS ID, NULL AS MS_MAY, NULL AS CA, NULL AS TU_GIO, NULL AS DEN_GIO, NULL AS THOI_GIAN_SUA_CHUA, NULL AS THOI_GIAN_SUA, NULL AS DownTimeTypeName, NULL AS TEN_NGUYEN_NHAN,  NULL AS HIEN_TUONG
	ORDER BY TGDM.TU_GIO
END	
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spCheckDatetimeOverLoad')
   exec('CREATE PROCEDURE spCheckDatetimeOverLoad AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spCheckDatetimeOverLoad
	 @MS_MAY NVARCHAR(30) ,
	@TGio DATETIME = NULL,
	@DGio DATETIME = NULL
AS 
BEGIN
	
	SELECT TU_GIO,DEN_GIO FROM dbo.THOI_GIAN_DUNG_MAY WHERE TU_GIO BETWEEN DATEADD(DAY,-30,@TGio) AND DATEADD(DAY,30,@TGio)
	UNION
	SELECT @TGio,@DGio
	ORDER BY TU_GIO

END	
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spDownTimeType')
   exec('CREATE PROCEDURE spDownTimeType AS BEGIN SET NOCOUNT ON; END')
GO
ALTER	PROCEDURE spDownTimeType
	@Loai NVARCHAR(50) = 'grd',
	@ID BIGINT = 3,
	@DownTimeTypeName NVARCHAR(250) = '-1',
	@DownTimeTypeNameA NVARCHAR(250) = '-1',
	@DownTimeTypeNameH NVARCHAR(250) = '-1',
	@Note NVARCHAR(500) = '-1',
	@Planned BIT = 0
AS
BEGIN
--Get luoi 
IF UPPER(@Loai) = UPPER('Grd')
BEGIN
   SELECT ID_DownTime, DownTimeTypeName, DownTimeTypeNameA, DownTimeTypeNameH, Note,Planned FROM dbo.DownTimeType ORDER BY DownTimeTypeName
END

--Save
IF UPPER(@Loai) = UPPER('Save')
BEGIN
--THEM
	IF @ID = -1
	BEGIN
		INSERT INTO	dbo.DownTimeType ( DownTimeTypeName, DownTimeTypeNameA,
		                            DownTimeTypeNameH, Note,Planned)
		VALUES(@DownTimeTypeName,@DownTimeTypeNameA,@DownTimeTypeNameH, @Note,@Planned)
		SELECT SCOPE_IDENTITY();
	END
--SUA
	ELSE
	BEGIN
		UPDATE dbo.DownTimeType SET DownTimeTypeName = @DownTimeTypeName,DownTimeTypeNameA = @DownTimeTypeNameA,DownTimeTypeNameH = @DownTimeTypeNameH, Note = @Note,Planned = @Planned
		WHERE ID_DownTime = @ID
		SELECT @ID;
	END
	END

--Delete 
IF UPPER(@Loai) = UPPER('Delete')
BEGIN
	IF EXISTS (SELECT	* FROM dbo.NGUYEN_NHAN_DUNG_MAY WHERE DownTimeTypeID = @ID)
	BEGIN
		SELECT 1 AS TT		
	END
	ELSE
	BEGIN
		DELETE dbo.DownTimeType WHERE ID_DownTime = @ID
		DBCC CHECKIDENT (DownTimeType,RESEED,0)
		DBCC CHECKIDENT (DownTimeType,RESEED)
		SELECT 0 AS TT		
	END
END	

END

GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spDownTimeCause')
   exec('CREATE PROCEDURE spDownTimeCause AS BEGIN SET NOCOUNT ON; END')
GO
ALTER	PROCEDURE spDownTimeCause
	@Loai NVARCHAR(50) = 'grd',
	@ID INT = 3,
	@TEN_NGUYEN_NHAN NVARCHAR(250) = '-1',
	@TEN_NGUYEN_NHANA NVARCHAR(250) = '-1',
	@DINH_MUC DECIMAL(18,2) = 0,
	@AUTO_CYCLE INT = 0,
	@DownTimeTypeID INT = '-1',
	@HU_HONG BIT =1, 
	@BTDK BIT = 1,
	@CauseCode NVARCHAR(50) ='',
	@MS_LOAI_MAY NVARCHAR(30) ='',
	 @NNgu INT = 0
AS
BEGIN
--Get luoi
IF UPPER(@Loai) = UPPER('Grd')
BEGIN
	SELECT A.MS_NGUYEN_NHAN, A.CauseCode,A.TEN_NGUYEN_NHAN, A.TEN_NGUYEN_NHAN_ANH,A.DefineLevel AS DINH_MUC, ISNULL(HU_HONG,0) AS HU_HONG, ISNULL(BTDK,0) AS BTDK,
           ISNULL(A.MS_LOAI_MAY,'') AS MS_LOAI_MAY,C.TEN_LOAI_MAY, A.DownTimeTypeID,  CASE @NNgu WHEN 1 THEN B.DownTimeTypeName WHEN 2 THEN ISNULL(NULLIF(B.DownTimeTypeNameA, ''), B.DownTimeTypeName) ELSE ISNULL(NULLIF(B.DownTimeTypeNameH, ''), B.DownTimeTypeName)
            END AS DownTimeTypeName
	 FROM dbo.NGUYEN_NHAN_DUNG_MAY A 
	 INNER JOIN dbo.DownTimeType B ON B.ID_DownTime = A.DownTimeTypeID
	 LEFT JOIN dbo.LOAI_MAY C ON C.MS_LOAI_MAY = A.MS_LOAI_MAY
	 ORDER BY A.TEN_NGUYEN_NHAN
END
--Save
IF UPPER(@Loai) = UPPER('Save')
BEGIN
--THEM
	IF @ID = -1
	BEGIN
		INSERT INTO	dbo.NGUYEN_NHAN_DUNG_MAY ( TEN_NGUYEN_NHAN, HU_HONG, BTDK,
		                                    TEN_NGUYEN_NHAN_ANH,DefineLevel,CauseCode, MS_LOAI_MAY,
		                                    DownTimeTypeID )
		VALUES(@TEN_NGUYEN_NHAN, @HU_HONG, @BTDK,
		                                    @TEN_NGUYEN_NHANA,@DINH_MUC,@CauseCode, @MS_LOAI_MAY,
		                                    @DownTimeTypeID)
		SELECT SCOPE_IDENTITY();
	END
--SUA
	ELSE
	BEGIN
		UPDATE dbo.NGUYEN_NHAN_DUNG_MAY SET
		TEN_NGUYEN_NHAN =@TEN_NGUYEN_NHAN, HU_HONG=@HU_HONG, BTDK=@BTDK,
		TEN_NGUYEN_NHAN_ANH = @TEN_NGUYEN_NHANA,DefineLevel =@DINH_MUC, MS_LOAI_MAY =@MS_LOAI_MAY,
		DownTimeTypeID = @DownTimeTypeID,CauseCode =@CauseCode
		WHERE MS_NGUYEN_NHAN = @ID
		SELECT @ID;
	END
	END

--Delete 
IF UPPER(@Loai) = UPPER('Delete')
BEGIN
	IF EXISTS (SELECT	* FROM dbo.THOI_GIAN_DUNG_MAY WHERE MS_NGUYEN_NHAN = @ID)
	BEGIN
		SELECT 1 AS TT		
	END
	ELSE
	BEGIN
		DELETE dbo.NGUYEN_NHAN_DUNG_MAY WHERE MS_NGUYEN_NHAN = @ID
		DBCC CHECKIDENT (NGUYEN_NHAN_DUNG_MAY,RESEED,0)
		DBCC CHECKIDENT (NGUYEN_NHAN_DUNG_MAY,RESEED)
		SELECT 0 AS TT		
	END
END	

END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetDownTimeType')
   exec('CREATE PROCEDURE spGetDownTimeType AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetDownTimeType
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (SELECT ID_DownTime, CASE @NNgu WHEN 0 THEN DownTimeTypeName WHEN 1 THEN ISNULL(DownTimeTypeNameA,DownTimeTypeName) WHEN 2 THEN	 ISNULL(DownTimeTypeNameH,DownTimeTypeName) END AS DownTimeTypeName  FROM dbo.DownTimeType
UNION
SELECT -1,N'< ALL >') A
ORDER BY A.ID_DownTime
END
ELSE
BEGIN
SELECT ID_DownTime, CASE @NNgu WHEN 0 THEN DownTimeTypeName WHEN 1 THEN ISNULL(DownTimeTypeNameA,DownTimeTypeName) WHEN 2 THEN	 ISNULL(DownTimeTypeNameH,DownTimeTypeName) END AS DownTimeTypeName  FROM dbo.DownTimeType
ORDER BY ID_DownTime
END	
END	
GO


