

CREATE PROCEDURE [dbo].[spGetDanhSachThaiSanCaNhan]
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@ID_CN INT = 22
AS
BEGIN
	SELECT TDTS.* FROM THEO_DOI_THAI_SAN TDTS
					LEFT JOIN CONG_NHAN CN ON TDTS.ID_CN = CN.ID_CN
	WHERE TDTS.ID_CN = @ID_CN
END
GO

