
--DELETE dbo.GIA_TRI_TS_GSTT
--DBCC CHECKIDENT (GIA_TRI_TS_GSTT, RESEED, 0);
--DELETE dbo.CAU_TRUC_THIET_BI_TS_GSTT
--DELETE dbo.THONG_SO_GSTT
--DROP TABLE #TMPDL
--DELETE dbo.MAY_LOAI_BTPN_CONG_VIEC
--DELETE dbo.MAY_LOAI_BTPN
--DELETE dbo.CAU_TRUC_THIET_BI_CONG_VIEC
--DELETE dbo.CONG_VIEC
--DELETE dbo.CAU_TRUC_THIET_BI


INSERT INTO dbo.CAU_TRUC_THIET_BI(MS_MAY,MS_BO_PHAN,TEN_BO_PHAN,SO_LUONG,MS_BO_PHAN_CHA,RUN_TIME,TEN_BO_PHAN_ANH,TEN_BO_PHAN_HOA,HIEU_LUC)
SELECT DISTINCT MS_MAY,MS_BP,TEN_BP,1,MS_BP_CHA,0,TEN_BP,TEN_BP,1 FROM dbo.TMPCT WHERE MS_MAY IS NOT NULL

----------------------------------------DINH_TINH-------------------------------------------------------
INSERT INTO dbo.THONG_SO_GSTT(MS_TS_GSTT,TEN_TS_GSTT,MS_DV_DO,LOAI_TS,GHI_CHU,MS_BP_GSTT,MS_LOAI_CV,TEN_TS_GSTT_ANH,TEN_TS_GSTT_HOA)
SELECT ROW_NUMBER() OVER (ORDER BY T.TEN_CV) AS ID,T.TEN_CV,NULL,1,T.NOI_DUNG_KIEM_TRA,1,T.LOAI_CV,T.TEN_CV,T.TEN_CV
FROM (SELECT DISTINCT TEN_CV,NOI_DUNG_KIEM_TRA,(SELECT MS_LOAI_CV FROM dbo.LOAI_CONG_VIEC WHERE TEN_LOAI_CV = LOAI_CV) AS LOAI_CV FROM dbo.TMPGS WHERE GSTT = 1 AND ISNULL(DINH_LUONG, 0) = 0) AS T;

DECLARE @RowCount INT
DECLARE @CurrentRow INT
DECLARE @String NVARCHAR(500)
DECLARE @Delimiter NVARCHAR(10) = ';'
DECLARE @Value NVARCHAR(500)

-- Lấy tổng số dòng trong bảng
SELECT @RowCount = MAX(CONVERT(INT,MS_TS_GSTT)) FROM dbo.THONG_SO_GSTT

-- Khởi tạo biến đếm dòng
SET @CurrentRow = 1

-- Vòng lặp WHILE để duyệt qua từng dòng
WHILE @CurrentRow <= @RowCount
BEGIN
    -- Lấy dữ liệu từng dòng trong bảng
	INSERT INTO dbo.GIA_TRI_TS_GSTT(MS_TS_GSTT,TEN_GIA_TRI,DAT,GHI_CHU)VALUES(@CurrentRow,'OK',1,'')
     SELECT @String = GHI_CHU +';' FROM dbo.THONG_SO_GSTT WHERE MS_TS_GSTT = @CurrentRow
WHILE CHARINDEX(@Delimiter, @String) > 0
BEGIN
    SET @Value = LTRIM(RTRIM(SUBSTRING(@String, 1, CHARINDEX(@Delimiter, @String) - 1)))
    SET @String = SUBSTRING(@String, CHARINDEX(@Delimiter, @String) + LEN(@Delimiter), LEN(@String))
    INSERT INTO dbo.GIA_TRI_TS_GSTT(MS_TS_GSTT,TEN_GIA_TRI,DAT,GHI_CHU)VALUES(@CurrentRow,UPPER(LEFT(@Value, 1)) + LOWER(SUBSTRING(@Value, 2, LEN(@Value))),0,'')
END
    -- Tăng giá trị biến đếm dòng
    SET @CurrentRow = @CurrentRow + 1
END



INSERT INTO dbo.CAU_TRUC_THIET_BI_TS_GSTT(MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE,THOI_GIAN,MS_UU_TIEN,NGAY_GS_CUOI)
SELECT DISTINCT A.MS_MAY,A.MS_BP,MS_TS_GSTT,1,NULL,NULL,NULL,A.CHU_KY,(SELECT MS_DV_TG FROM dbo.DON_VI_THOI_GIAN WHERE TEN_DV_TG = A.DVTG),0,'',1,A.DINH_MUC,2,NULL FROM dbo.TMPGS A
INNER JOIN dbo.THONG_SO_GSTT B ON A.NOI_DUNG_KIEM_TRA = B.GHI_CHU AND A.TEN_CV = B.TEN_TS_GSTT
WHERE  GSTT = 1 AND ISNULL(DINH_LUONG, 0) = 0


----------------------------------------DINH_LUONG-------------------------------------------------------
INSERT INTO dbo.THONG_SO_GSTT(MS_TS_GSTT,TEN_TS_GSTT,MS_DV_DO,LOAI_TS,GHI_CHU,MS_BP_GSTT,MS_LOAI_CV,TEN_TS_GSTT_ANH,TEN_TS_GSTT_HOA)
SELECT (SELECT MAX(CONVERT(INT,MS_TS_GSTT)) FROM dbo.THONG_SO_GSTT) + ROW_NUMBER() OVER (ORDER BY T.TEN_CV) AS ID,T.TEN_CV,(SELECT TOP 1 MS_DV_DO FROM dbo.DON_VI_DO WHERE TEN_DV_DO = DON_VI_DO),0,T.NOI_DUNG_KIEM_TRA,1,T.LOAI_CV,T.TEN_CV,T.TEN_CV
FROM (SELECT DISTINCT TEN_CV,NOI_DUNG_KIEM_TRA,(SELECT MS_LOAI_CV FROM dbo.LOAI_CONG_VIEC WHERE TEN_LOAI_CV = LOAI_CV) AS LOAI_CV,DON_VI_DO FROM dbo.TMPGS WHERE GSTT = 1 AND DINH_LUONG = 1) AS T;


SELECT DISTINCT B.MS_TS_GSTT,A.MS_MAY,A.MS_BP,A.TEN_BP,A.LOAI_CV,A.TEN_CV,A.GSTT,A.CHU_KY,A.DVTG,A.DINH_MUC,A.DINH_LUONG,A.DON_VI_DO,A.NOI_DUNG_KIEM_TRA
INTO #TMPDL
FROM dbo.TMPGS A
INNER JOIN dbo.THONG_SO_GSTT B ON A.NOI_DUNG_KIEM_TRA = B.GHI_CHU AND A.TEN_CV = B.TEN_TS_GSTT
WHERE  GSTT = 1 AND A.DINH_LUONG = 1 AND B.LOAI_TS = 0


--DECLARE @RowCount INT
--DECLARE @CurrentRow INT
--DECLARE @String NVARCHAR(500)
--DECLARE @Delimiter NVARCHAR(10) = ';'
--DECLARE @Value NVARCHAR(500)
DECLARE @STT INT

SELECT @RowCount = MAX(CONVERT(INT,MS_TS_GSTT)),@CurrentRow =  MIN(CONVERT(INT,MS_TS_GSTT)) FROM #TMPDL
WHILE @CurrentRow <= @RowCount
BEGIN
    SET @STT = 1
     SELECT @String = NOI_DUNG_KIEM_TRA +';' FROM dbo.#TMPDL WHERE MS_TS_GSTT = @CurrentRow
		WHILE CHARINDEX(@Delimiter, @String) > 0
		BEGIN
			SET @Value = LTRIM(RTRIM(SUBSTRING(@String, 1, CHARINDEX(@Delimiter, @String) - 1)))
			SET @String = SUBSTRING(@String, CHARINDEX(@Delimiter, @String) + LEN(@Delimiter), LEN(@String))

			INSERT INTO dbo.CAU_TRUC_THIET_BI_TS_GSTT(MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE,THOI_GIAN,MS_UU_TIEN,NGAY_GS_CUOI)
			SELECT DISTINCT TOP 1 MS_MAY,MS_BP,@CurrentRow,@STT,LEFT(@Value, CHARINDEX('/', @Value) - 1),SUBSTRING(@Value, CHARINDEX('/', @Value) + 1, CHARINDEX('/', @Value, CHARINDEX('/', @Value) + 1) - CHARINDEX('/', @Value) - 1),REVERSE(SUBSTRING(REVERSE(@Value), 1, CHARINDEX('/', REVERSE(@Value)) - 1)),CHU_KY,(SELECT MS_DV_TG FROM dbo.DON_VI_THOI_GIAN WHERE TEN_DV_TG = DVTG),
			CASE  @STT WHEN 1 THEN 1 ELSE 0 end ,'',1,DINH_MUC,2,NULL FROM #TMPDL
			SET @STT = @STT + 1
		END
			SET @CurrentRow = @CurrentRow + 1
END


INSERT INTO dbo.CONG_VIEC(MS_CV,MA_CV,KY_HIEU_CV,MS_LOAI_CV,MO_TA_CV,MO_TA_CV_ANH,MO_TA_CV_HOA,MS_LOAI_MAY,THOI_GIAN_DU_KIEN,AN_TOAN,DINH_MUC,NGOAI_TE,SO_NGUOI)
SELECT ROW_NUMBER() OVER (ORDER BY T.TEN_CV),ROW_NUMBER() OVER (ORDER BY T.TEN_CV),NULL,T.LOAI_CV,T.TEN_CV,T.TEN_CV,T.TEN_CV,NULL,T.DINH_MUC,0,0,'VND',1
FROM (SELECT DISTINCT TEN_CV,(SELECT MS_LOAI_CV FROM dbo.LOAI_CONG_VIEC WHERE TEN_LOAI_CV = LOAI_CV) AS LOAI_CV,DINH_MUC FROM dbo.TMPGS WHERE GSTT = 0) AS T;

INSERT INTO dbo.CAU_TRUC_THIET_BI_CONG_VIEC(MS_MAY,MS_BO_PHAN,MS_CV,GHI_CHU,ACTIVE,TG_KH)
SELECT A.MS_MAY,A.MS_BP,B.MS_CV,'',1,A.DINH_MUC FROM dbo.TMPGS A
INNER JOIN  dbo.CONG_VIEC B ON A.TEN_CV = B.MO_TA_CV WHERE ISNULL(A.GSTT,0) = 0

INSERT INTO dbo.MAY_LOAI_BTPN(MS_MAY,MS_LOAI_BT,NGAY_CUOI,SO_NGAY)
SELECT DISTINCT A.MS_MAY,(SELECT MS_LOAI_BT FROM dbo.LOAI_BAO_TRI WHERE TEN_LOAI_BT = CHU_KY + ' '+ DVTG),'01/01/2023',NULL FROM dbo.TMPGS A
INNER JOIN  dbo.CONG_VIEC B ON A.TEN_CV = B.MO_TA_CV WHERE ISNULL(A.GSTT,0) = 0


INSERT INTO dbo.MAY_LOAI_BTPN_CONG_VIEC(MS_MAY,MS_LOAI_BT,MS_CV,MS_BO_PHAN)
SELECT DISTINCT A.MS_MAY,(SELECT MS_LOAI_BT FROM dbo.LOAI_BAO_TRI WHERE TEN_LOAI_BT = CHU_KY + ' '+ DVTG),B.MS_CV,A.MS_BP FROM dbo.TMPGS A
INNER JOIN  dbo.CONG_VIEC B ON A.TEN_CV = B.MO_TA_CV WHERE ISNULL(A.GSTT,0) = 0


