DECLARE @nam INT = 2020

SELECT SUM(A.THOI_GIAN_SUA_CHUA) AS TGDM FROM dbo.THOI_GIAN_NGUNG_MAY A
INNER JOIN dbo.MAY B ON B.MS_MAY = A.MS_MAY WHERE YEAR(A.NGAY) = @nam

SELECT COUNT(*) AS TGDM FROM dbo.THOI_GIAN_NGUNG_MAY_SO_LAN A
INNER JOIN dbo.MAY B ON B.MS_MAY = A.MS_MAY WHERE YEAR(A.NGAY) = @nam

SELECT SUM(CHI_PHI_PHU_TUNG+CHI_PHI_VAT_TU+CHI_PHI_NHAN_CONG+CHI_PHI_DV+CHI_PHI_KHAC) CP_KH FROM dbo.PHIEU_BAO_TRI A
INNER JOIN dbo.PHIEU_BAO_TRI_CHI_PHI B ON B.MS_PHIEU_BAO_TRI = A.MS_PHIEU_BAO_TRI
INNER JOIN dbo.LOAI_BAO_TRI C ON C.MS_LOAI_BT = A.MS_LOAI_BT
WHERE YEAR(A.NGAY_LAP) = @nam AND C.HU_HONG = 0


SELECT SUM(CHI_PHI_PHU_TUNG+CHI_PHI_VAT_TU+CHI_PHI_NHAN_CONG+CHI_PHI_DV+CHI_PHI_KHAC) CP_BT FROM dbo.PHIEU_BAO_TRI A
INNER JOIN dbo.PHIEU_BAO_TRI_CHI_PHI B ON B.MS_PHIEU_BAO_TRI = A.MS_PHIEU_BAO_TRI
INNER JOIN dbo.LOAI_BAO_TRI C ON C.MS_LOAI_BT = A.MS_LOAI_BT
WHERE YEAR(A.NGAY_LAP) = @nam AND C.HU_HONG = 1

SELECT COUNT(*) SLBT FROM dbo.PHIEU_BAO_TRI WHERE YEAR(NGAY_LAP) = @nam 

