--DELETE THOI_GIAN_NGUNG_MAY_CT
--DELETE NGUYEN_NHAN_DUNG_MAY
--DELETE FROM dbo.THOI_GIAN_NGUNG_MAY
--DROP TABLE THOI_GIAN_NGUNG_MAY_CT
--DROP TABLE NGUYEN_NHAN_DUNG_MAY
--DROP TABLE THOI_GIAN_NGUNG_MAY
--DROP TABLE dbo.THOI_GIAN_NGUNG_MAY_CODE
--DROP TABLE dbo.THOI_GIAN_NGUNG_MAY_DAILY_TMP
--DROP TABLE dbo.THOI_GIAN_NGUNG_MAY_DO_HU_HONG_THEO_MAY_TMP
--DROP TABLE dbo.THOI_GIAN_NGUNG_MAY_SO_LAN
--DROP TABLE dbo.THOI_GIAN_NGUNG_MAY_PHU_TUNG
--DROP TABLE dbo.NGUYEN_NHAN_DUNG_MAY
--DROP TABLE dbo.DownTimeType
IF NOT  EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo' AND Table_Name ='DownTimeType')
BEGIN
	CREATE TABLE [dbo].[DownTimeType]
	(
	[ID_DownTime] [int] NOT NULL IDENTITY(1, 1),
	[DownTimeTypeName] [nvarchar] (250)  NULL,
	[DownTimeTypeNameA] [nvarchar] (250)  NULL,
	[DownTimeTypeNameH] [nvarchar] (250)  NULL,
	[Note] [nvarchar] (500)  NULL,
	[Planned] [bit] NULL,
	[NoEdit] [bit] NULL,
	[SORT] [int] NULL
	) ON [PRIMARY]
	ALTER TABLE [dbo].[DownTimeType] ADD CONSTRAINT [PK_DownTimeType] PRIMARY KEY CLUSTERED ([ID_DownTime]) ON [PRIMARY]
END

IF NOT  EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo' AND Table_Name ='NGUYEN_NHAN_DUNG_MAY')
BEGIN
     --thuc thi lệnh
CREATE TABLE [dbo].[NGUYEN_NHAN_DUNG_MAY]
(
[MS_NGUYEN_NHAN] [int] NOT NULL IDENTITY(1, 1),
[TEN_NGUYEN_NHAN] [nvarchar] (250)   NULL,
[HU_HONG] [bit] NOT NULL CONSTRAINT [DF_NGUYEN_NHAN_DUNG_MAY_HU_HONG] DEFAULT ((0)),
[BTDK] [bit] NULL CONSTRAINT [DF__NGUYEN_NHA__BTDK__2630A1B7] DEFAULT ((0)),
[TEN_NGUYEN_NHAN_ANH] [nvarchar] (250)   NULL,
[MAC_DINH] [bit] NULL CONSTRAINT [DF_NGUYEN_NHAN_DUNG_MAY_MAC_DINH] DEFAULT ((0)),
[Planned] [int] NULL,
[CauseCode] [nvarchar] (50)   NULL,
[DownTimeTypeID] [int] NULL,
[SORT] [int] NULL,
[DefineLevel] [decimal] (18, 2) NULL,
[MS_LOAI_MAY] NVARCHAR(20)
) ON [PRIMARY]
ALTER TABLE [dbo].[NGUYEN_NHAN_DUNG_MAY] ADD CONSTRAINT [PK_NGUYEN_NHAN_DUNG_MAY] PRIMARY KEY CLUSTERED ([MS_NGUYEN_NHAN]) ON [PRIMARY]
ALTER TABLE [dbo].[NGUYEN_NHAN_DUNG_MAY] ADD CONSTRAINT [FK_NGUYEN_NHAN_DUNG_MAY_DownTimeType] FOREIGN KEY ([DownTimeTypeID]) REFERENCES [dbo].[DownTimeType] ([ID_DownTime])
ALTER TABLE [dbo].[NGUYEN_NHAN_DUNG_MAY] ADD CONSTRAINT [FK_NGUYEN_NHAN_DUNG_MAY_StopType] FOREIGN KEY ([Planned]) REFERENCES [dbo].[StopType] ([ID])
END

IF NOT  EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo' AND Table_Name ='LOAI_MAY_NGUYEN_NHAN')
BEGIN
CREATE TABLE [dbo].[LOAI_MAY_NGUYEN_NHAN]
(
[MS_LOAI_MAY] [nvarchar] (20)  NOT NULL,
[MS_NGUYEN_NHAN] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[LOAI_MAY_NGUYEN_NHAN] ADD CONSTRAINT [PK_LOAI_MAY_NGUYEN_NHAN] PRIMARY KEY CLUSTERED ([MS_LOAI_MAY], [MS_NGUYEN_NHAN]) ON [PRIMARY]
ALTER TABLE [dbo].[LOAI_MAY_NGUYEN_NHAN] ADD CONSTRAINT [FK_LOAI_MAY_NGUYEN_NHAN_LOAI_MAY] FOREIGN KEY ([MS_LOAI_MAY]) REFERENCES [dbo].[LOAI_MAY] ([MS_LOAI_MAY])
ALTER TABLE [dbo].[LOAI_MAY_NGUYEN_NHAN] ADD CONSTRAINT [FK_LOAI_MAY_NGUYEN_NHAN_NGUYEN_NHAN_DUNG_MAY] FOREIGN KEY ([MS_NGUYEN_NHAN]) REFERENCES [dbo].[NGUYEN_NHAN_DUNG_MAY] ([MS_NGUYEN_NHAN])
END



IF NOT  EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES Where Table_Schema = 'dbo' AND Table_Name ='THOI_GIAN_DUNG_MAY')
BEGIN
CREATE TABLE [dbo].[THOI_GIAN_DUNG_MAY]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MS_MAY] [nvarchar] (30)  NOT NULL,
[CaID] [int] NULL,
[NGAY_DUNG] [datetime] NULL,
[TU_GIO] [datetime] NOT NULL,
[TU_GIO_GOC] [datetime] NULL,
[DEN_GIO] [datetime] NOT NULL,
[DEN_GIO_GOC] [datetime] NULL,
[THOI_GIAN_SUA_CHUA] [float] NULL,
[THOI_GIAN_SUA] [float] NULL,
[MS_NGUYEN_NHAN] [int] NULL,
[MS_NGUYEN_NHAN_GOC] [int] NULL,
[USERNAME] [nvarchar] (30) NOT NULL,
[ID_CHA] [bigint] NULL,
TRUONG_CA NVARCHAR(50) NULL,
NGUOI_GIAI_QUYET NVARCHAR(50) NULL,
HIEN_TUONG NVARCHAR(250) NULL,
NGUYEN_NHAN_CU_THE NVARCHAR(250) NULL,
[MS_HE_THONG] INT NULL,
[MS_TO] INT NULL,
MS_N_XUONG  NVARCHAR(50),
[MS_PBT] NVARCHAR(20) NULL,
[CLOSED] BIT NULL,
[GHI_CHU] [nvarchar] (500)  NULL,
[UserEdit] [nvarchar] (30)  NULL,
[DateEdit] [datetime] NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[THOI_GIAN_DUNG_MAY] ADD CONSTRAINT [PK_THOI_GIAN_DUNG_MAY] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
ALTER TABLE [dbo].[THOI_GIAN_DUNG_MAY] ADD CONSTRAINT [FK_THOI_GIAN_DUNG_MAY_NGUYEN_NHAN_DUNG_MAY] FOREIGN KEY ([MS_NGUYEN_NHAN]) REFERENCES [dbo].[NGUYEN_NHAN_DUNG_MAY] ([MS_NGUYEN_NHAN])
END


