IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'DI_CHUYEN_THIET_BI')
BEGIN
    CREATE TABLE [dbo].[DI_CHUYEN_THIET_BI]
(
[NGAY_CHUYEN] [datetime] NOT NULL,
[KHO_DI] [nvarchar] (50)   NOT NULL,
[KHO_DEN] [nvarchar] (50)   NOT NULL,
[MS_MAY] [nvarchar] (30)   NOT NULL,
[NGAY_NHAN] [datetime] NULL,
[USER_CHUYEN] [nvarchar] (30)   NULL,
[USER_NHAN] [nvarchar] (30)   NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[DI_CHUYEN_THIET_BI] ADD CONSTRAINT [PK_DI_CHUYEN_THIET_BI] PRIMARY KEY CLUSTERED ([NGAY_CHUYEN], [KHO_DI], [KHO_DEN], [MS_MAY]) ON [PRIMARY]
END

